/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/granny.glb --types --keepnames -o src/components/Granny.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import { RigidBody } from '@react-three/rapier';
import { useGrannyState } from '../store/useGrannyState';
import { useDayState } from '../store/useDayState';
import { usePlayerState } from '../store/usePlayerState';
import { useRef, useState } from 'react';
import type { RapierRigidBody } from '@react-three/rapier';

type GLTFResult = GLTF & {
  nodes: {
    leg: THREE.Mesh;
    leg_2: THREE.Mesh;
    head: THREE.Mesh;
    body: THREE.Mesh;
    arm: THREE.Mesh;
    weapon: THREE.Mesh;
    arm_2: THREE.Mesh;
  };
  materials: {
    body: THREE.MeshStandardMaterial;
    ['Material.017']: THREE.MeshStandardMaterial;
    dress: THREE.MeshStandardMaterial;
    wood2: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Granny(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/granny.glb') as GLTFResult;
  const { grannySpawnArray } = useGrannyState();
  const { nextDay } = useDayState();
  const { playerSpawnArray } = usePlayerState();
  const grannyRef = useRef<RapierRigidBody>(null);
  const [isCatching, setIsCatching] = useState(false);

  const handlePlayerCollision = (playerRigidBody: any) => {
    if (isCatching) return;
    
    setIsCatching(true);
    
    // Wait 1 second, then trigger next day and respawn
    setTimeout(() => {
      nextDay();
      
      // Reset player position after short delay
      setTimeout(() => {
        if (playerRigidBody && playerSpawnArray) {
          playerRigidBody.setTranslation({ x: playerSpawnArray[0], y: playerSpawnArray[1], z: playerSpawnArray[2] }, true);
          playerRigidBody.setLinvel({ x: 0, y: 0, z: 0 }, true);
          playerRigidBody.setAngvel({ x: 0, y: 0, z: 0 }, true);
        }
        setIsCatching(false);
      }, 500);
    }, 1000);
  };

  return (
    <RigidBody
      ref={grannyRef}
      type="fixed"
      position={grannySpawnArray || [0, 0, 0]}
      colliders="cuboid"
      sensor
      onIntersectionEnter={(e) => {
        if (e.other.rigidBodyObject?.name === 'player') {
          handlePlayerCollision(e.other.rigidBody);
        }
      }}
    >
      <group {...props} dispose={null}>
      <mesh
        name="leg"
        geometry={nodes.leg.geometry}
        material={materials.body}
        position={[-36.104, 2.786, -1.837]}
        scale={[0.097, 0.183, 0.097]}
      />
      <mesh
        name="leg_2"
        geometry={nodes.leg_2.geometry}
        material={materials.body}
        position={[-35.609, 2.786, -1.837]}
        scale={[0.097, 0.183, 0.097]}
      />
      <mesh
        name="head"
        geometry={nodes.head.geometry}
        material={materials['Material.017']}
        position={[-35.857, 5.717, -1.838]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.413, 0.47, 0.413]}
      />
      <mesh
        name="body"
        geometry={nodes.body.geometry}
        material={materials.dress}
        position={[-35.857, 4.217, -1.838]}
        scale={[0.619, 0.705, 0.619]}
      />
      <mesh
        name="arm"
        geometry={nodes.arm.geometry}
        material={materials.body}
        position={[-35.357, 4.698, -1.838]}
        rotation={[0, 0, 0.848]}
        scale={[0.075, 0.569, 0.069]}
      />
      <mesh
        name="weapon"
        geometry={nodes.weapon.geometry}
        material={materials.wood2}
        position={[-35.135, 4.77, -1.607]}
        rotation={[0.714, -0.509, 0.4]}
        scale={[0.089, 0.68, 0.093]}
      />
      <mesh
        name="arm_2"
        geometry={nodes.arm_2.geometry}
        material={materials.body}
        position={[-36.367, 4.698, -1.838]}
        rotation={[Math.PI, 0, -2.293]}
        scale={[0.075, 0.569, 0.069]}
      />
    </group>
    </RigidBody>
  );
}

useGLTF.preload('/models/granny.glb');
