/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/granny.glb --types --keepnames -o src/components/Granny.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import { RigidBody } from '@react-three/rapier';
import { useGrannyState } from '../store/useGrannyState';
import { useDayState } from '../store/useDayState';
import { usePlayerState } from '../store/usePlayerState';
import { useGameSettings } from '../store/useGameSettings';
import { useScreamer } from '../store/useScreamer';
import { useDoors } from '../store/useDoors';
import { useBedHiding } from '../store/useBedHiding';
import { useClosetHiding } from '../store/useClosetHiding';
import { useRef, useState, useEffect } from 'react';
import type { RapierRigidBody } from '@react-three/rapier';
import { useFrame, useThree } from '@react-three/fiber';
import { navigationSystem } from '../utils/navigation';
import type { Difficulty } from '../store/useGameSettings';
import type React from 'react';

type GLTFResult = GLTF & {
  nodes: {
    Cube050: THREE.Mesh;
    Cube050_1: THREE.Mesh;
    Cube050_2: THREE.Mesh;
    Cube050_3: THREE.Mesh;
  };
  materials: {
    body: THREE.MeshStandardMaterial;
    ['Material.017']: THREE.MeshStandardMaterial;
    dress: THREE.MeshStandardMaterial;
    wood2: THREE.MeshStandardMaterial;
  };
};

const difficultySettings: Record<Difficulty, { investigationSpeed: number }> = {
  practice: { investigationSpeed: 0 },
  easy: { investigationSpeed: 7 },
  normal: { investigationSpeed: 10 },
  hard: { investigationSpeed: 13 },
};

export function Granny(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/granny.glb') as unknown as GLTFResult;
  const {
    grannySpawnArray,
    currentPath,
    currentTargetIndex,
    targetPoint,
    mode,
    patrolSpeed,
    investigationSpeed,
    waitTime,
    waitTimer,
    hasSeenPlayer,
    setCurrentPath,
    setCurrentTargetIndex,
    setTargetPoint,
    setMode,
    setWaitTimer,
    resetPath,
    setInvestigationSpeed,
    setHasSeenPlayer,
  } = useGrannyState();
  const { nextDay } = useDayState();
  const { playerSpawnArray, triggerCameraReset } = usePlayerState();
  const { inGameMenuOpen, volume, difficulty } = useGameSettings();
  const { isScreamerActive, startScreamer, endScreamer } = useScreamer();
  const { openDoor, doors } = useDoors();
  const { isHiding: isHidingInBed } = useBedHiding();
  const { isHiding: isHidingInCloset } = useClosetHiding();
  const { scene } = useThree();
  const grannyRef = useRef<RapierRigidBody>(null);
  const groupRef = useRef<THREE.Group>(null);
  const [isCatching, setIsCatching] = useState(false);
  const [isInitialized, setIsInitialized] = useState(false);
  const screamerTriggered = useRef(false);
  const doorObjectsCache = useRef<Map<string, THREE.Object3D>>(new Map());
  const cacheInitialized = useRef(false);
  const playerRigidBodyRef = useRef<any>(null);

  const isHiding = isHidingInBed || isHidingInCloset;

  console.log(isHiding);

  // Set investigation speed based on difficulty
  useEffect(() => {
    setInvestigationSpeed(difficultySettings[difficulty].investigationSpeed);
  }, [difficulty, setInvestigationSpeed]);

  // Initialize patrol on mount
  useEffect(() => {
    const initPatrol = () => {
      if (!isInitialized && grannyRef.current && grannySpawnArray) {
        // Respawn granny at spawn location
        grannyRef.current.setTranslation(
          {
            x: grannySpawnArray[0],
            y: grannySpawnArray[1],
            z: grannySpawnArray[2],
          },
          true
        );

        const currentPos = grannyRef.current.translation();
        console.log('Granny current position:', currentPos);

        const randomPoint = navigationSystem.getRandomPointOnNavMesh();
        console.log('Random point on navmesh:', randomPoint);

        if (randomPoint) {
          setTargetPoint(randomPoint);
          const path = navigationSystem.findPath(
            new THREE.Vector3(currentPos.x, currentPos.y, currentPos.z),
            randomPoint
          );
          console.log('Path found:', path);
          if (path.length > 0) {
            setCurrentPath(path);
          }
        }
        setIsInitialized(true);
      }
    };

    const timeout = setTimeout(initPatrol, 2000);
    return () => clearTimeout(timeout);
  }, [isInitialized, setCurrentPath, setTargetPoint, grannySpawnArray]);

  // Patrol and investigation logic
  useFrame((_, delta) => {
    if (!grannyRef.current || !isInitialized || isCatching || inGameMenuOpen || isScreamerActive)
      return;

    const currentPos = grannyRef.current.translation();
    const currentPosition = new THREE.Vector3(currentPos.x, currentPos.y, currentPos.z);
    const currentSpeed = mode === 'investigating' ? investigationSpeed : patrolSpeed;

    // Cache player rigid body reference
    if (!playerRigidBodyRef.current) {
      scene.traverse((obj) => {
        if (obj.name === 'player') {
          playerRigidBodyRef.current = obj;
        }
      });
    }

    // Vision logic - check if player is visible (works in any mode)
    // If player is hiding and wasn't seen before hiding, skip vision check
    const shouldCheckVision = !(isHiding && !hasSeenPlayer);

    const playerRigidBody = playerRigidBodyRef.current;
    if (playerRigidBody && shouldCheckVision) {
      const playerPosition = new THREE.Vector3(
        playerRigidBody.position.x,
        playerRigidBody.position.y,
        playerRigidBody.position.z
      );
      const distanceToPlayer = currentPosition.distanceTo(playerPosition);

      // Check distance (15-20 meters)
      if (distanceToPlayer < 30) {
        // Check angle - 90 degrees cone in front of Granny
        const directionToPlayer = new THREE.Vector3()
          .subVectors(playerPosition, currentPosition)
          .normalize();
        const grannyForward = new THREE.Vector3(0, 0, 1).applyAxisAngle(
          new THREE.Vector3(0, 1, 0),
          groupRef.current?.rotation.y || 0
        );
        const angle = grannyForward.angleTo(directionToPlayer);

        // 180 degrees = PI (full front hemisphere vision)
        if (angle < Math.PI) {
          // Check for obstacles using raycaster
          // Add eye-level offset to Granny's position for better vision detection
          const grannyEyePosition = currentPosition.clone();
          grannyEyePosition.y += 1.5; // Granny's eye level
          
          const playerEyePosition = playerPosition.clone();
          playerEyePosition.y += 0.5; // Player's torso level
          
          const directionToPlayerEyes = new THREE.Vector3()
            .subVectors(playerEyePosition, grannyEyePosition)
            .normalize();
          const distanceToPlayerEyes = grannyEyePosition.distanceTo(playerEyePosition);
          
          const raycaster = new THREE.Raycaster(
            grannyEyePosition,
            directionToPlayerEyes,
            0,
            distanceToPlayerEyes
          );
          const intersects = raycaster.intersectObjects(scene.children, true);

          // Check if vision is blocked by walls/floors/ceilings
          let blocked = false;
          for (const intersect of intersects) {
            const obj = intersect.object;
            const objName = obj.name; // Don't use toLowerCase, compare original names

            // Only walls, floors, and ceilings block vision
            const isWall =
              objName.includes('attic_plank') ||
              objName.includes('room_door') ||
              objName.includes('barn_door') ||
              objName.includes('bed') ||
              objName.includes('box') ||
              objName.includes('black_wall') ||
              objName.includes('table') ||
              [
                'Walls004',
                'Walls011',
                'Cube115',
                'Cube105',
                'Cube101',
                'Cube112',
                'Cube130',
                'Cube035',
                'Cube036',
                'Cube125',
                'Cube124',
                'Cube126',
                'Cube116',
                'Plane013',
                'Plane016',
                'Plane015',
                'Plane014',
                'Floor',
                'Floor005',
                'Floor001',
                'Floor002',
                'Floor003',
                'Floor004',
                'Walls008',
                'Walls010',
                'Walls009',
                'Cube053',
                'Cube052',
                'Cube095',
                'Cube096',
                'Cube093',
                'Cube057',
                'Cube111',
                'Cube079',
                'Cube081',
                'Plane006',
                'Cube051',
                'Cube056',
                'Cube047',
                'Cube049',
                'Cube054',
                'Walls005',
                'Walls003',
                'Walls002',
                'Walls006',
                'Walls007',
                'Plane012',
                'Plane011',
                'Plane010',
                'Plane001',
                'Walls',
                'Plane005',
              ].includes(objName);

            // Check if wall is between Granny and player
            if (isWall && intersect.distance < distanceToPlayerEyes - 0.5) {
              blocked = true;
              console.log('Vision blocked by:', obj.name, 'at distance:', intersect.distance);
              break;
            }
          }

          // If player is visible, chase them
          if (!blocked) {
            // Mark that Granny has seen the player
            if (!hasSeenPlayer) {
              setHasSeenPlayer(true);
            }
            
            // Use player floor position (subtract player height to get floor level)
            const playerFloorPosition = playerPosition.clone();
            playerFloorPosition.y -= 1.7; // Player height

            // Find closest point on navmesh to player floor position
            let closestPoint = navigationSystem.getClosestPointOnNavMesh(playerFloorPosition);

            // If no point found on navmesh, try original player position
            if (!closestPoint) {
              closestPoint = navigationSystem.getClosestPointOnNavMesh(playerPosition);
            }

            // Always update path when player is visible (regardless of current mode)
            if (closestPoint) {
              const path = navigationSystem.findPath(currentPosition, closestPoint);
              if (path.length > 0) {
                setMode('investigating');
                setTargetPoint(closestPoint);
                setCurrentPath(path);
                setCurrentTargetIndex(0);
              }
            }
          }
        }
      }
    }

    // Build door objects cache once
    if (!cacheInitialized.current) {
      scene.traverse((object) => {
        if (
          object.userData.isDoor &&
          object.userData.doorId &&
          !doorObjectsCache.current.has(object.userData.doorId)
        ) {
          doorObjectsCache.current.set(object.userData.doorId, object);
        }
      });
      if (doorObjectsCache.current.size > 0) {
        cacheInitialized.current = true;
      }
    }

    // Check for nearby closed doors and open them
    doorObjectsCache.current.forEach((doorObject, doorId) => {
      if (!doorId.includes('room_door') && !doorId.includes('barn_door')) return;

      const doorState = doors.get(doorId);

      if (doorState && !doorState.isOpen && !doorState.isRotating) {
        const doorPos = new THREE.Vector3();
        doorObject.getWorldPosition(doorPos);
        const distanceToDoor = currentPosition.distanceTo(doorPos);

        if (distanceToDoor < 3) {
          openDoor(doorId);
        }
      }
    });

    // Waiting mode - stand still for waitTime seconds (but still check for player vision above)
    if (mode === 'waiting') {
      if (waitTimer >= waitTime) {
        // Finished waiting, return to patrol
        setMode('patrol');
        setWaitTimer(0);
        resetPath();
        const randomPoint = navigationSystem.getRandomPointOnNavMesh();
        if (randomPoint) {
          setTargetPoint(randomPoint);
          const path = navigationSystem.findPath(currentPosition, randomPoint);
          if (path.length > 0) {
            setCurrentPath(path);
          }
        }
      } else {
        setWaitTimer(waitTimer + delta);
      }
      // Don't return here - let vision logic override waiting if player is spotted
      // Only skip movement logic if still in waiting mode after vision check
      if (mode === 'waiting') return;
    }

    // If we have a path, follow it
    if (currentPath.length > 0 && currentTargetIndex < currentPath.length) {
      const waypoint = currentPath[currentTargetIndex];
      const direction = new THREE.Vector3().subVectors(waypoint, currentPosition);
      const distance = direction.length();

      // Check if reached waypoint
      if (distance < 0.3) {
        if (currentTargetIndex < currentPath.length - 1) {
          setCurrentTargetIndex(currentTargetIndex + 1);
        } else {
          // Reached final destination
          if (mode === 'investigating') {
            // Start waiting at sound location
            setMode('waiting');
            setWaitTimer(0);
          } else {
            // In patrol mode, pick new random point
            resetPath();
            const randomPoint = navigationSystem.getRandomPointOnNavMesh();
            if (randomPoint) {
              setTargetPoint(randomPoint);
              const path = navigationSystem.findPath(currentPosition, randomPoint);
              if (path.length > 0) {
                setCurrentPath(path);
              }
            }
          }
        }
      } else {
        // Move towards waypoint
        direction.normalize();
        const movement = direction.multiplyScalar(currentSpeed * delta);

        grannyRef.current.setNextKinematicTranslation({
          x: currentPos.x + movement.x,
          y: currentPos.y + movement.y,
          z: currentPos.z + movement.z,
        });

        // Rotate to face movement direction
        if (groupRef.current && movement.length() > 0.001) {
          const angle = Math.atan2(movement.x, movement.z);
          groupRef.current.rotation.y = angle;
        }
      }
    } else if (!targetPoint) {
      // No path and no target, pick new random point (only in patrol mode)
      if (mode === 'patrol') {
        const randomPoint = navigationSystem.getRandomPointOnNavMesh();
        if (randomPoint) {
          setTargetPoint(randomPoint);
          const path = navigationSystem.findPath(currentPosition, randomPoint);
          if (path.length > 0) {
            setCurrentPath(path);
          }
        }
      }
    } else if (mode === 'investigating' && currentPath.length === 0) {
      // We have a target but no path, build path (for sound investigation)
      const path = navigationSystem.findPath(currentPosition, targetPoint);
      if (path.length > 0) {
        setCurrentPath(path);
      }
    }
  });

  const handlePlayerCollision = (playerRigidBody: any) => {
    if (isCatching || screamerTriggered.current) return;

    setIsCatching(true);
    screamerTriggered.current = true;

    // Get Granny position for camera look-at
    const grannyPos = grannyRef.current?.translation();
    if (grannyPos) {
      const grannyPosition = new THREE.Vector3(grannyPos.x, grannyPos.y, grannyPos.z);
      startScreamer(grannyPosition);
    }

    // Play scream sound
    const audio = new Audio('/sounds/granny_scream.mp3');
    audio.volume = (volume / 100) * 0.7;
    audio.play().catch((err) => console.warn('Scream sound play failed:', err));

    // After 3 seconds, trigger next day and respawn
    setTimeout(() => {
      // End screamer before next day
      endScreamer();

      nextDay();

      // Reset player position after short delay
      setTimeout(() => {
        if (playerRigidBody && playerSpawnArray) {
          playerRigidBody.setTranslation(
            { x: playerSpawnArray[0], y: playerSpawnArray[1], z: playerSpawnArray[2] },
            true
          );
          playerRigidBody.setLinvel({ x: 0, y: 0, z: 0 }, true);
          playerRigidBody.setAngvel({ x: 0, y: 0, z: 0 }, true);
          triggerCameraReset();
        }
        setIsCatching(false);
        screamerTriggered.current = false;
        resetPath();
        setIsInitialized(false);
      }, 500);
    }, 3000);
  };

  return (
    <>
      <RigidBody
        ref={grannyRef}
        type="kinematicPosition"
        position={grannySpawnArray || [-17.524, -0.774, -24.65]}
        colliders="cuboid"
        sensor
        onIntersectionEnter={(e) => {
          if (e.other.rigidBodyObject?.name === 'player') {
            handlePlayerCollision(e.other.rigidBody);
          }
        }}
      >
        <group ref={groupRef} {...props} dispose={null}>
          <group name="granny">
            <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials.body} />
            <mesh
              name="Cube050_1"
              geometry={nodes.Cube050_1.geometry}
              material={materials['Material.017']}
            />
            <mesh name="Cube050_2" geometry={nodes.Cube050_2.geometry} material={materials.dress} />
            <mesh name="Cube050_3" geometry={nodes.Cube050_3.geometry} material={materials.wood2} />
          </group>
        </group>
      </RigidBody>

      {/* Debug: Visualize path */}
      {currentPath.map((point, index) => (
        <mesh key={index} position={[point.x, point.y, point.z]}>
          <sphereGeometry args={[0.1, 8, 8]} />
          <meshBasicMaterial color={index === currentTargetIndex ? 'red' : 'yellow'} />
        </mesh>
      ))}

      {/* Debug: Visualize target point */}
      {targetPoint && (
        <mesh position={[targetPoint.x, targetPoint.y, targetPoint.z]}>
          <sphereGeometry args={[0.2, 8, 8]} />
          <meshBasicMaterial color="green" />
        </mesh>
      )}
    </>
  );
}

useGLTF.preload('/models/granny.glb');
