/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hauntedHouse.glb --types --keepnames -o src/components/HauntedHouse.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import { RigidBody, CuboidCollider } from '@react-three/rapier';
import { useHauntedHouse } from '../hooks/useHauntedHouse';
import { Door } from './Door';
import { Items } from './Items';
import { AtticPlanks } from './AtticPlanks';
import { useGuillotine } from '../store/useGuillotine';
import { useItems } from '../store/useItems';
import { useShields } from '../store/useShields';
import { usePlank } from '../store/usePlank';
import { useEscapeDoor } from '../store/useEscapeDoor';
import { useWires } from '../store/useWires';
import { useWell } from '../store/useWell';
import { useEffect, useRef, useState } from 'react';
import { useFrame, type ThreeElements } from '@react-three/fiber';
import type { RapierRigidBody } from '@react-three/rapier';
import { useGameSettings } from '../store/useGameSettings';
import { useDayState } from '../store/useDayState';
import { usePlayerState } from '../store/usePlayerState';

type GLTFResult = GLTF & {
  nodes: {
    navmesh: THREE.Mesh;
    attic_trigger: THREE.Mesh;
    Plane005: THREE.Mesh;
    Cube047: THREE.Mesh;
    Cube048: THREE.Mesh;
    Cube049: THREE.Mesh;
    Cube051: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube054: THREE.Mesh;
    Plane009: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube056: THREE.Mesh;
    attic_wire: THREE.Mesh;
    attic_wire_cut: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    Cube011_2: THREE.Mesh;
    Cube010: THREE.Mesh;
    Walls: THREE.Mesh;
    Floor: THREE.Mesh;
    Floor001: THREE.Mesh;
    Walls001: THREE.Mesh;
    Window003: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube215: THREE.Mesh;
    Cube215_1: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube004: THREE.Mesh;
    Floor002: THREE.Mesh;
    Walls002: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube213: THREE.Mesh;
    Cube213_1: THREE.Mesh;
    Walls004: THREE.Mesh;
    Floor004: THREE.Mesh;
    Walls005: THREE.Mesh;
    Window006: THREE.Mesh;
    Floor003: THREE.Mesh;
    Cube214: THREE.Mesh;
    Cube214_1: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube042: THREE.Mesh;
    Cube043: THREE.Mesh;
    Cube045: THREE.Mesh;
    Walls003: THREE.Mesh;
    Cube058: THREE.Mesh;
    Plane010: THREE.Mesh;
    Cube057: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Cube060: THREE.Mesh;
    Cube044: THREE.Mesh;
    Cube061: THREE.Mesh;
    Cube062: THREE.Mesh;
    Walls006: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
    Walls007: THREE.Mesh;
    Cube075: THREE.Mesh;
    Cube076: THREE.Mesh;
    Cube077: THREE.Mesh;
    Cube078: THREE.Mesh;
    Cube113: THREE.Mesh;
    Cube127: THREE.Mesh;
    Cube130: THREE.Mesh;
    Cube128: THREE.Mesh;
    Cube129: THREE.Mesh;
    Cube131: THREE.Mesh;
    Cube132: THREE.Mesh;
    Cube216: THREE.Mesh;
    Cube216_1: THREE.Mesh;
    Cube218: THREE.Mesh;
    Cube218_1: THREE.Mesh;
    Cube219: THREE.Mesh;
    Cube219_1: THREE.Mesh;
    Cube220: THREE.Mesh;
    Cube220_1: THREE.Mesh;
    Cube221: THREE.Mesh;
    Cube221_1: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube007: THREE.Mesh;
    main_door: THREE.Mesh;
    closet_for_hiding_door003: THREE.Mesh;
    closet_for_hiding003: THREE.Mesh;
    Plane015: THREE.Mesh;
    Cube080: THREE.Mesh;
    Cube079: THREE.Mesh;
    Plane016: THREE.Mesh;
    Cube081: THREE.Mesh;
    Cube091: THREE.Mesh;
    Cube092: THREE.Mesh;
    Cube093: THREE.Mesh;
    Cube094: THREE.Mesh;
    Cube095: THREE.Mesh;
    Cube096: THREE.Mesh;
    Cube097: THREE.Mesh;
    Cube101: THREE.Mesh;
    Cube103: THREE.Mesh;
    Cube110: THREE.Mesh;
    Cube111: THREE.Mesh;
    Cube105: THREE.Mesh;
    Cube112: THREE.Mesh;
    Floor005: THREE.Mesh;
    Walls008: THREE.Mesh;
    Cube114: THREE.Mesh;
    Walls010: THREE.Mesh;
    Plane018: THREE.Mesh;
    Walls009: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube115: THREE.Mesh;
    Cube116: THREE.Mesh;
    Cube117: THREE.Mesh;
    Cube118: THREE.Mesh;
    Cube121: THREE.Mesh;
    Cube119: THREE.Mesh;
    Cube120: THREE.Mesh;
    Cube174: THREE.Mesh;
    Cube174_1: THREE.Mesh;
    Cube122: THREE.Mesh;
    Cube123: THREE.Mesh;
    Cube124: THREE.Mesh;
    Cube125: THREE.Mesh;
    Cube126: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube011: THREE.Mesh;
    plank001: THREE.Mesh;
    attic_plank_4001: THREE.Mesh;
    attic_plank_3001: THREE.Mesh;
    attic_plank_2001: THREE.Mesh;
    attic_plank_1001: THREE.Mesh;
    Cube243: THREE.Mesh;
    Cube243_1: THREE.Mesh;
    Cube243_2: THREE.Mesh;
    vase_table001: THREE.Mesh;
    vase001: THREE.Mesh;
    closet_for_hiding_door001: THREE.Mesh;
    closet_for_hiding001: THREE.Mesh;
    room_door001: THREE.Mesh;
    room_door002: THREE.Mesh;
    Cube255: THREE.Mesh;
    Cube255_1: THREE.Mesh;
    Cube256: THREE.Mesh;
    Cube256_1: THREE.Mesh;
    nightstand001: THREE.Mesh;
    table001: THREE.Mesh;
    closet_for_hiding_door002: THREE.Mesh;
    closet_for_hiding002: THREE.Mesh;
    room_door003: THREE.Mesh;
    room_door004: THREE.Mesh;
    Cube263: THREE.Mesh;
    Cube263_1: THREE.Mesh;
    Cube264: THREE.Mesh;
    Cube264_1: THREE.Mesh;
    closet001: THREE.Mesh;
    Cube266: THREE.Mesh;
    Cube266_1: THREE.Mesh;
    Cube266_2: THREE.Mesh;
    table002: THREE.Mesh;
    chair001: THREE.Mesh;
    Cube269: THREE.Mesh;
    Cube269_1: THREE.Mesh;
    Cube270: THREE.Mesh;
    Cube270_1: THREE.Mesh;
    nightstand002: THREE.Mesh;
    Cylinder023: THREE.Mesh;
    Cylinder023_1: THREE.Mesh;
    Cube272: THREE.Mesh;
    Cube272_1: THREE.Mesh;
    Cube272_2: THREE.Mesh;
    Cube273: THREE.Mesh;
    Cube273_1: THREE.Mesh;
    Cube274: THREE.Mesh;
    Cube274_1: THREE.Mesh;
    nightstand003: THREE.Mesh;
    box001: THREE.Mesh;
    box002: THREE.Mesh;
    box003: THREE.Mesh;
    room_door_small001: THREE.Mesh;
    Cone002: THREE.Mesh;
    Cone002_1: THREE.Mesh;
    Cylinder024: THREE.Mesh;
    Cylinder024_1: THREE.Mesh;
    rope001: THREE.Mesh;
    handle001: THREE.Mesh;
    bucket001: THREE.Mesh;
    blade001: THREE.Mesh;
    barn_door001: THREE.Mesh;
    microwave_door001: THREE.Mesh;
    kitchen_cupboard_door001: THREE.Mesh;
    kitchen_cupboard_door002: THREE.Mesh;
    kitchen_cupboard_door003: THREE.Mesh;
    kitchen_cupboard_door004: THREE.Mesh;
    kitchen_cupboard_door005: THREE.Mesh;
    kitchen_cupboard_door006: THREE.Mesh;
    closet002: THREE.Mesh;
    Cube290: THREE.Mesh;
    Cube290_1: THREE.Mesh;
    Cube291: THREE.Mesh;
    Cube291_1: THREE.Mesh;
    table003: THREE.Mesh;
    Cube294: THREE.Mesh;
    Cube294_1: THREE.Mesh;
    Cube295: THREE.Mesh;
    Cube295_1: THREE.Mesh;
    closet003: THREE.Mesh;
    table004: THREE.Mesh;
    chair002: THREE.Mesh;
    Cube299: THREE.Mesh;
    Cube299_1: THREE.Mesh;
    Cube300: THREE.Mesh;
    Cube300_1: THREE.Mesh;
    nightstand004: THREE.Mesh;
    nightstand005: THREE.Mesh;
    Cube303: THREE.Mesh;
    Cube303_1: THREE.Mesh;
    Cube304: THREE.Mesh;
    Cube304_1: THREE.Mesh;
    Cube305: THREE.Mesh;
    Cube305_1: THREE.Mesh;
    Cube306: THREE.Mesh;
    Cube306_1: THREE.Mesh;
    closet004: THREE.Mesh;
    closet005: THREE.Mesh;
    Cube309: THREE.Mesh;
    Cube309_1: THREE.Mesh;
    Cube310: THREE.Mesh;
    Cube310_1: THREE.Mesh;
    chair003: THREE.Mesh;
    chair004: THREE.Mesh;
    chair005: THREE.Mesh;
    chair006: THREE.Mesh;
    chair007: THREE.Mesh;
    chair008: THREE.Mesh;
    table005: THREE.Mesh;
    table006: THREE.Mesh;
    Cube319: THREE.Mesh;
    Cube319_1: THREE.Mesh;
    Cube320: THREE.Mesh;
    Cube320_1: THREE.Mesh;
    nightstand006: THREE.Mesh;
    room_door005: THREE.Mesh;
    plank002: THREE.Mesh;
    hatch001: THREE.Mesh;
    safe_door001: THREE.Mesh;
    Cube326: THREE.Mesh;
    Cube326_1: THREE.Mesh;
    Cube327: THREE.Mesh;
    Cube327_1: THREE.Mesh;
    nightstand007: THREE.Mesh;
    room_door_small002: THREE.Mesh;
    shield: THREE.Mesh;
    shield_wire: THREE.Mesh;
    shield_wire_cut: THREE.Mesh;
    shield002: THREE.Mesh;
    shield003: THREE.Mesh;
    shield_wire002: THREE.Mesh;
    shield_wire003: THREE.Mesh;
    shield_wire_cut002: THREE.Mesh;
    shield_wire_cut003: THREE.Mesh;
    nightstand008: THREE.Mesh;
    nightstand009: THREE.Mesh;
    Cube006_1: THREE.Mesh;
    Cube006_2: THREE.Mesh;
    Cube007_1: THREE.Mesh;
    Cube007_2: THREE.Mesh;
    cut_indicators: THREE.Mesh;
    cut_indicator_1: THREE.Mesh;
    cut_indicator_2: THREE.Mesh;
    door_wire: THREE.Mesh;
    wood_plank: THREE.Mesh;
    wood_plank001: THREE.Mesh;
    Cube038_1: THREE.Mesh;
    Cube038_2: THREE.Mesh;
    Cube038_3: THREE.Mesh;
    terminal: THREE.Mesh;
    terminal_indicator: THREE.Mesh;
    door_wire_cut: THREE.Mesh;
    black_wall: THREE.Mesh;
    black_wall_2: THREE.Mesh;
    black_wall_3: THREE.Mesh;
    Cube053_1: THREE.Mesh;
    Cube053_2: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube015_1: THREE.Mesh;
    Cube057_1: THREE.Mesh;
    Cube057_2: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cube059_1: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube055_1: THREE.Mesh;
    Cube068: THREE.Mesh;
    Cube068_1: THREE.Mesh;
    Cube075_1: THREE.Mesh;
    Cube075_2: THREE.Mesh;
    Cube077_1: THREE.Mesh;
    Cube077_2: THREE.Mesh;
    Cube079_1: THREE.Mesh;
    Cube079_2: THREE.Mesh;
    Cube080_1: THREE.Mesh;
    Cube080_2: THREE.Mesh;
    Cube070: THREE.Mesh;
    Cube070_1: THREE.Mesh;
    Cube041_1: THREE.Mesh;
    Cube041_2: THREE.Mesh;
    Cube045_1: THREE.Mesh;
    Cube045_2: THREE.Mesh;
    Cube037_1: THREE.Mesh;
    Cube037_2: THREE.Mesh;
    Cube039_1: THREE.Mesh;
    Cube039_2: THREE.Mesh;
  };
  materials: {
    navmesh: THREE.MeshStandardMaterial;
    floor: THREE.MeshStandardMaterial;
    walls: THREE.MeshStandardMaterial;
    wood2: THREE.MeshStandardMaterial;
    wire: THREE.MeshStandardMaterial;
    window: THREE.MeshStandardMaterial;
    painting: THREE.MeshStandardMaterial;
    ['walls 2']: THREE.MeshStandardMaterial;
    plumbing: THREE.MeshStandardMaterial;
    ['metal 2.001']: THREE.MeshStandardMaterial;
    ground: THREE.MeshStandardMaterial;
    wood3: THREE.MeshStandardMaterial;
    safe: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    bed: THREE.MeshStandardMaterial;
    ['bed 2']: THREE.MeshStandardMaterial;
    vase: THREE.MeshStandardMaterial;
    ['metal 2']: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    lamp: THREE.MeshStandardMaterial;
    lamp2: THREE.MeshStandardMaterial;
    box: THREE.MeshStandardMaterial;
    well: THREE.MeshStandardMaterial;
    rope: THREE.MeshStandardMaterial;
    shield: THREE.MeshStandardMaterial;
    ['shield.002']: THREE.MeshStandardMaterial;
    ['shield.003']: THREE.MeshStandardMaterial;
    ['wire.002']: THREE.MeshStandardMaterial;
    ['wire.003']: THREE.MeshStandardMaterial;
    ['wood2.001']: THREE.MeshStandardMaterial;
    ['metal.001']: THREE.MeshStandardMaterial;
    red_light: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    ['black.001']: THREE.MeshStandardMaterial;
    ['wood2.003']: THREE.MeshStandardMaterial;
    ['wood2.004']: THREE.MeshStandardMaterial;
    ['wood2.005']: THREE.MeshStandardMaterial;
    ['wood2.006']: THREE.MeshStandardMaterial;
    ['wood2.007']: THREE.MeshStandardMaterial;
    ['wood2.008']: THREE.MeshStandardMaterial;
    ['wood2.009']: THREE.MeshStandardMaterial;
    ['wood2.010']: THREE.MeshStandardMaterial;
    ['wood2.011']: THREE.MeshStandardMaterial;
    ['wood2.012']: THREE.MeshStandardMaterial;
    ['wood2.013']: THREE.MeshStandardMaterial;
    ['wood2.014']: THREE.MeshStandardMaterial;
    ['wood2.015']: THREE.MeshStandardMaterial;
    ['wood2.016']: THREE.MeshStandardMaterial;
    ['wood2.017']: THREE.MeshStandardMaterial;
    ['metal.002']: THREE.MeshStandardMaterial;
    ['metal.003']: THREE.MeshStandardMaterial;
    ['metal.004']: THREE.MeshStandardMaterial;
    ['metal.005']: THREE.MeshStandardMaterial;
    ['metal.006']: THREE.MeshStandardMaterial;
    ['metal.007']: THREE.MeshStandardMaterial;
    ['metal.008']: THREE.MeshStandardMaterial;
    ['metal.009']: THREE.MeshStandardMaterial;
    ['metal.010']: THREE.MeshStandardMaterial;
    ['metal.011']: THREE.MeshStandardMaterial;
    ['metal.012']: THREE.MeshStandardMaterial;
    ['metal.013']: THREE.MeshStandardMaterial;
    ['metal.014']: THREE.MeshStandardMaterial;
    ['metal.015']: THREE.MeshStandardMaterial;
    ['metal.016']: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function HauntedHouse(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/hauntedHouse.glb') as unknown as GLTFResult;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const itemsModel = useGLTF('/models/items.glb') as any; // Load items model for watermelon

  useHauntedHouse(nodes);
  
  const { volume } = useGameSettings();
  const { nextDay } = useDayState();
  const { playerSpawnArray, triggerCameraReset } = usePlayerState();

  const { watermelonPlaced, bladeDropped, itemRevealed, dropBlade, revealItem } = useGuillotine();
  const { itemInsideWatermelon } = useItems();
  const { activeShieldId, initializeActiveShield } = useShields();
  const { isChippedOff, plankPlaced } = usePlank();
  const { cardSwiped, wiresCut, lockOpened } = useEscapeDoor();
  const { doorWireCut, shieldWireCut, atticWireCut } = useWires();
  const { handleSet, handleRotation, bucketHeight, updateWellProgress } = useWell();
  const bladeRef = useRef<THREE.Mesh>(null);
  const [bladePosition, setBladePosition] = useState(0.083); // Initial Y position
  const [animating, setAnimating] = useState(false);
  const plankRef = useRef<THREE.Mesh>(null);
  const [plankYOffset, setPlankYOffset] = useState(0);
  const [plankAnimating, setPlankAnimating] = useState(false);
  const hatchRef = useRef<RapierRigidBody>(null);
  const [hatchFallen, setHatchFallen] = useState(false);
  const [hatchVisible, setHatchVisible] = useState(true);
  const hatchFallTimeRef = useRef<number>(0);
  const animationStartedRef = useRef(false);
  const plankAnimationStartedRef = useRef(false);
  const bucketRef = useRef<RapierRigidBody>(null);
  const atticTriggerActivated = useRef(false);
  
  const box1LastSound = useRef(0);
  const box2LastSound = useRef(0);
  const box3LastSound = useRef(0);
  const plank1LastSound = useRef(0);
  const plank2LastSound = useRef(0);
  const soundCooldown = 500; // milliseconds
  const startupGracePeriod = useRef(true);

  // Initialize random shield selection on mount
  useEffect(() => {
    initializeActiveShield();
  }, [initializeActiveShield]);

  // Disable startup grace period after 2 seconds
  useEffect(() => {
    const timer = setTimeout(() => {
      startupGracePeriod.current = false;
    }, 2000);
    return () => clearTimeout(timer);
  }, []);
  
  // Handle attic trigger activation
  const handleAtticTrigger = (playerBody: RapierRigidBody) => {
    if (atticTriggerActivated.current) return;
    atticTriggerActivated.current = true;
    
    // Wait 1 second before showing black screen and respawning
    setTimeout(() => {
      nextDay();
      
      // Reset player position immediately after showing day message
      setTimeout(() => {
        if (playerSpawnArray) {
          playerBody.setTranslation({ x: playerSpawnArray[0], y: playerSpawnArray[1], z: playerSpawnArray[2] }, true);
          playerBody.setLinvel({ x: 0, y: 0, z: 0 }, true);
          playerBody.setAngvel({ x: 0, y: 0, z: 0 }, true);
          triggerCameraReset();
        }
        atticTriggerActivated.current = false;
      }, 100);
    }, 1000);
  };
  
  const playBoxSound = (lastSoundRef: React.MutableRefObject<number>) => {
    if (startupGracePeriod.current) return;
    const now = Date.now();
    if (now - lastSoundRef.current > soundCooldown) {
      const audio = new Audio('/sounds/box.mp3');
      audio.volume = (volume / 100) * 0.5;
      audio.play().catch(err => console.warn('Box sound play failed:', err));
      lastSoundRef.current = now;
    }
  };
  
  const playPlankSound = (lastSoundRef: React.MutableRefObject<number>) => {
    if (startupGracePeriod.current) return;
    const now = Date.now();
    if (now - lastSoundRef.current > soundCooldown) {
      const audio = new Audio('/sounds/plank.mp3');
      audio.volume = (volume / 100) * 0.5;
      audio.play().catch(err => console.warn('Plank sound play failed:', err));
      lastSoundRef.current = now;
    }
  };

  // Start blade animation when watermelon is placed
  useEffect(() => {
    if (watermelonPlaced && !bladeDropped && !animationStartedRef.current) {
      animationStartedRef.current = true;
      const audio = new Audio('/sounds/blade.mp3');
      audio.volume = (volume / 100) * 0.5;
      audio.play().catch(err => console.warn('Blade sound play failed:', err));
      
      requestAnimationFrame(() => setAnimating(true));
      setTimeout(() => {
        dropBlade();
      }, 1500); // Blade takes 1.5 seconds to drop
      
      // Make watermelon disappear and reveal item after blade drops
      setTimeout(() => {
        revealItem();
        // Set the position for the hidden item to drop in front of guillotine
        const itemDropPosition: [number, number, number] = [-11, -1.55, -28.3];
        useItems.setState((state) => ({
          droppedPositions: {
            ...state.droppedPositions,
            [itemInsideWatermelon]: itemDropPosition
          }
        }));
      }, 1600); // Slightly after blade completes drop
    }
  }, [watermelonPlaced, bladeDropped, dropBlade, revealItem, itemInsideWatermelon]);

  // Start plank animation when attic wire is cut
  useEffect(() => {
    if (atticWireCut && !plankAnimating && !plankAnimationStartedRef.current) {
      plankAnimationStartedRef.current = true;
      requestAnimationFrame(() => setPlankAnimating(true));
    }
  }, [atticWireCut, plankAnimating]);

  // Animate the blade dropping and plank moving
  useFrame((_state, delta) => {
    if (animating && !bladeDropped) {
      setBladePosition((prev) => {
        const newPos = prev - delta * 1.5; // Drop speed
        if (newPos <= 0.083 - 1.45) { // Drop 1.45m
          setAnimating(false);
          return 0.083 - 1.45;
        }
        return newPos;
      });
    }
    
    // Animate plank moving up
    if (plankAnimating && plankYOffset < 0.7) {
      setPlankYOffset((prev) => {
        const newOffset = prev + delta * 0.5; // Move speed
        if (newOffset >= 0.7) {
          setPlankAnimating(false);
          return 0.7;
        }
        return newOffset;
      });
    }
    
    // Handle hatch falling and disappearing
    if (hatchFallen && hatchVisible) {
      hatchFallTimeRef.current += delta;
      if (hatchFallTimeRef.current >= 6) {
        setHatchVisible(false);
      }
    }
    
    // Update well progress
    updateWellProgress(delta);
    
    // Update bucket position
    if (bucketRef.current) {
      bucketRef.current.setNextKinematicTranslation({ 
        x: -16.202, 
        y: -6.604 + bucketHeight, 
        z: -30.295 
      });
    }
  });

  return (
    <>
      {/* Navmesh - no physics, hidden, available for AI pathfinding */}
      <mesh
        name="navmesh"
        geometry={nodes.navmesh.geometry}
        material={materials.navmesh}
        position={[-13.92, -3.029, -24.248]}
        visible={false}
      />

      {/* Interactive Doors - outside fixed RigidBody */}
      {/* Main door - escape door */}
      <RigidBody type="fixed" colliders="trimesh" position={[9.188, -0.116, -2.992]}>
        <mesh
          name="main_door"
          geometry={nodes.main_door.geometry}
          material={materials.wood2}
          rotation={[0, 0, Math.PI]}
          scale={[1, 1, 0.09]}
        />
      </RigidBody>
      <Door
        doorId="room_door001"
        geometry={nodes.room_door001.geometry}
        material={materials.wood2}
        position={[6.782, 4.859, -15.173]}
        rotation={[0, 0, Math.PI]}
        scale={[1, 1, 0.09]}
        openDirection={-1}
      />
      <Door
        doorId="room_door002"
        geometry={nodes.room_door002.geometry}
        material={materials.wood2}
        position={[9.049, 4.859, -15.173]}
        scale={[1, 1, 0.09]}
        openDirection={1}
      />
      <Door
        doorId="room_door003"
        geometry={nodes.room_door003.geometry}
        material={materials.wood2}
        position={[3.388, 4.859, -14.872]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[1, 1, 0.09]}
        openDirection={1}
      />
      <Door
        doorId="room_door004"
        geometry={nodes.room_door004.geometry}
        material={materials.wood2}
        position={[12.691, 4.859, -3.553]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={[1, 1, 0.09]}
        openDirection={1}
      />
      <Door
        doorId="room_door005"
        geometry={nodes.room_door005.geometry}
        material={materials.wood2}
        position={[16.134, -2.325, -31.93]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, 0.09]}
        openDirection={1}
      />
      <Door
        doorId="room_door_small001"
        geometry={nodes.room_door_small001.geometry}
        material={materials.wood2}
        position={[12.157, 4.859, -2.89]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1, 1, 0.051]}
        openDirection={-1}
      />
      <Door
        doorId="room_door_small002"
        geometry={nodes.room_door_small002.geometry}
        material={materials.wood2}
        position={[5.442, -0.116, -14.548]}
        rotation={[0, -1.571, 0]}
        scale={[1, 1, 0.051]}
        openDirection={1}
      />
      <Door
        doorId="barn_door001"
        geometry={nodes.barn_door001.geometry}
        material={materials.wood2}
        position={[-18.561, -1.215, -20.538]}
        scale={[1, 1, 0.031]}
        openDirection={1}
      />
      <Door
        doorId="closet_for_hiding_door001"
        geometry={nodes.closet_for_hiding_door001.geometry}
        material={materials['metal 2']}
        position={[5.233, 4.863, -23.203]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.026, 1, 0.595]}
        openDirection={-1}
      />
      <Door
        doorId="closet_for_hiding_door002"
        geometry={nodes.closet_for_hiding_door002.geometry}
        material={materials['metal 2']}
        position={[-4.494, 4.867, -12.066]}
        scale={[0.026, 1, 0.595]}
        openDirection={-1}
      />
      <Door
        doorId="closet_for_hiding_door003"
        geometry={nodes.closet_for_hiding_door003.geometry}
        material={materials['metal 2.001']}
        position={[9.334, -0.115, -11.228]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.026, 1, 0.595]}
        openDirection={1}
      />
      <Door
        doorId="safe_door001"
        geometry={nodes.safe_door001.geometry}
        material={materials.safe}
        position={[0.693, -6.215, -11.754]}
        openDirection={-1}
      />
      <Door
        doorId="microwave_door001"
        geometry={nodes.microwave_door001.geometry}
        material={materials.plumbing}
        position={[-4.346, 0.107, -11.632]}
        rotation={[0, -0.485, 0]}
        scale={[0.552, 0.276, 0.552]}
        openDirection={-1}
      />
      <Door
        doorId="kitchen_cupboard_door001"
        geometry={nodes.kitchen_cupboard_door001.geometry}
        material={materials.wood}
        position={[-3.197, -1.132, -12.888]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.01, 0.089, 0.046]}
        openDirection={-1}
      />
      <Door
        doorId="kitchen_cupboard_door002"
        geometry={nodes.kitchen_cupboard_door002.geometry}
        material={materials.wood}
        position={[-1.333, -1.132, -12.888]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.01, 0.089, 0.046]}
        openDirection={-1}
      />
      <Door
        doorId="kitchen_cupboard_door003"
        geometry={nodes.kitchen_cupboard_door003.geometry}
        material={materials.wood}
        position={[-1.334, 1.507, -12.888]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.01, 0.089, 0.046]}
        openDirection={-1}
      />
      <Door
        doorId="kitchen_cupboard_door004"
        geometry={nodes.kitchen_cupboard_door004.geometry}
        material={materials.wood}
        position={[-3.195, 1.507, -12.888]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.01, 0.089, 0.046]}
        openDirection={-1}
      />
      <Door
        doorId="kitchen_cupboard_door005"
        geometry={nodes.kitchen_cupboard_door005.geometry}
        material={materials.wood}
        position={[-3.628, -1.129, -9.945]}
        scale={[0.01, 0.089, 0.046]}
        openDirection={-1}
      />
      <Door
        doorId="kitchen_cupboard_door006"
        geometry={nodes.kitchen_cupboard_door006.geometry}
        material={materials.wood}
        position={[-3.628, -1.129, -6.276]}
        scale={[0.01, 0.089, 0.046]}
        openDirection={-1}
      />
      <Door
        doorId="closet_door002"
        geometry={nodes.Cube263.geometry}
        material={materials.wood2}
        position={[24.346, 4.876, -11.436]}
        rotation={[0, 0, -Math.PI]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube263_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door003"
        geometry={nodes.Cube264.geometry}
        material={materials.wood2}
        position={[24.346, 4.876, -14.363]}
        rotation={[Math.PI, 0, Math.PI]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube264_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door004"
        geometry={nodes.Cube290.geometry}
        material={materials.wood2}
        position={[-4.271, -0.092, -5.81]}
        rotation={[-Math.PI, 0, 0]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube290_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door005"
        geometry={nodes.Cube291.geometry}
        material={materials.wood2}
        position={[-4.271, -0.092, -2.883]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube291_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door006"
        geometry={nodes.Cube294.geometry}
        material={materials.wood2}
        position={[14.121, -0.097, -10.511]}
        rotation={[-Math.PI, 0, 0]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube294_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door007"
        geometry={nodes.Cube295.geometry}
        material={materials.wood2}
        position={[14.121, -0.097, -7.584]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube295_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door008"
        geometry={nodes.Cube305.geometry}
        material={materials.wood2}
        position={[-5.952, -0.097, -16.129]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube305_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door009"
        geometry={nodes.Cube306.geometry}
        material={materials.wood2}
        position={[-3.025, -0.097, -16.129]}
        rotation={[0, Math.PI / 2, 0]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube306_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door010"
        geometry={nodes.Cube309.geometry}
        material={materials.wood2}
        position={[2.654, -0.097, -23.16]}
        rotation={[0, -Math.PI / 2, 0]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube309_1.geometry} material={materials.metal} />
      </Door>
      <Door
        doorId="closet_door011"
        geometry={nodes.Cube310.geometry}
        material={materials.wood2}
        position={[5.581, -0.097, -23.16]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube310_1.geometry} material={materials.metal} />
      </Door>

      <RigidBody type="fixed" colliders="trimesh">
        <group {...props} dispose={null}>
          <mesh
            name="Plane005"
            geometry={nodes.Plane005.geometry}
            material={materials.floor}
            position={[6.279, 7.831, -10.075]}
          />
          <mesh
            name="Cube047"
            geometry={nodes.Cube047.geometry}
            material={materials.walls}
            position={[7.579, 6.737, -2.889]}
          />
          <mesh
            name="Cube048"
            geometry={nodes.Cube048.geometry}
            material={materials.wood2}
            position={[3.715, 5.338, -1.548]}
          />
          <mesh
            name="Cube049"
            geometry={nodes.Cube049.geometry}
            material={materials.walls}
            position={[8.025, 10.442, -11.491]}
          />
          <mesh
            name="Cube051"
            geometry={nodes.Cube051.geometry}
            material={materials.walls}
            position={[12.188, 10.666, -12.695]}
          />
          <mesh
            name="Plane006"
            geometry={nodes.Plane006.geometry}
            material={materials.walls}
            position={[15.113, 10.55, -11.526]}
          />
          <mesh
            name="Plane007"
            geometry={nodes.Plane007.geometry}
            material={materials.floor}
            position={[7.216, 13.027, -10.751]}
          />
          <mesh
            ref={plankRef}
            name="Plane008"
            geometry={nodes.Plane008.geometry}
            material={materials.wood2}
            position={[15.934, 10.743 + plankYOffset, -8.192]}
          />
          <mesh
            name="Cube052"
            geometry={nodes.Cube052.geometry}
            material={materials.walls}
            position={[3.321, 10.666, -16.979]}
          />
          <mesh
            name="Cube053"
            geometry={nodes.Cube053.geometry}
            material={materials.walls}
            position={[-1.358, 9.629, -11.078]}
          />
          <mesh
            name="Cube054"
            geometry={nodes.Cube054.geometry}
            material={materials.walls}
            position={[-3.27, 9.2, -12.494]}
          />
          <mesh
            name="Plane009"
            geometry={nodes.Plane009.geometry}
            material={materials.walls}
            position={[6.505, 5.754, -1.569]}
          />
          <mesh
            name="Cube050"
            geometry={nodes.Cube050.geometry}
            material={materials.walls}
            position={[12.188, 10.666, -11.231]}
          />
          <mesh
            name="Cube056"
            geometry={nodes.Cube056.geometry}
            material={materials.walls}
            position={[12.188, 10.666, -5.132]}
          />
          {/* <mesh name="attic_trigger" 
            geometry={nodes.attic_trigger.geometry}
            material={nodes.attic_trigger.material} 
            position={[8.114, 7.358, -8.506]} 
            scale={[1.47, 0.043, 1.47]}
            visible={false}
          /> */}
          {!atticWireCut && (
            <mesh name="attic_wire" geometry={nodes.attic_wire.geometry} material={materials.wire} position={[15.883, 10.13, -8.211]} />
          )}
          {atticWireCut && (
            <mesh name="attic_wire_cut" geometry={nodes.attic_wire_cut.geometry} material={materials.wire} position={[15.883, 10.13, -8.211]} />
          )}
          <group name="Window001" position={[1.531, 5.801, -24.407]}>
            <mesh name="Cube011_1" geometry={nodes.Cube011_1.geometry} material={materials.wood2} />
            <mesh
              name="Cube011_2"
              geometry={nodes.Cube011_2.geometry}
              material={materials.window}
            />
          </group>
          <mesh
            name="Cube010"
            geometry={nodes.Cube010.geometry}
            material={materials.painting}
            position={[7.76, 5.309, -20.354]}
          />
          <mesh
            name="Walls"
            geometry={nodes.Walls.geometry}
            material={materials['walls 2']}
            position={[-0.475, 5.309, -21.485]}
          />
          <mesh
            name="Floor"
            geometry={nodes.Floor.geometry}
            material={materials.floor}
            position={[-0.525, 2.727, -19.933]}
          />
          <mesh
            name="Floor001"
            geometry={nodes.Floor001.geometry}
            material={materials.floor}
            position={[-1.328, 2.721, -9.23]}
          />
          <mesh
            name="Walls001"
            geometry={nodes.Walls001.geometry}
            material={materials['walls 2']}
            position={[-0.582, 5.178, -9.681]}
          />
          <mesh
            name="Window003"
            geometry={nodes.Window003.geometry}
            material={materials.window}
            position={[3.211, 5.586, -8.919]}
          />
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials.plumbing}
            position={[1.026, 4.059, -4.63]}
          />
          <group name="Window005" position={[-5.676, 5.801, -9.285]} rotation={[0, Math.PI / 2, 0]}>
            <mesh name="Cube215" geometry={nodes.Cube215.geometry} material={materials.wood2} />
            <mesh
              name="Cube215_1"
              geometry={nodes.Cube215_1.geometry}
              material={materials.window}
            />
          </group>
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.plumbing}
            position={[2.991, 4.242, -10.298]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.043, 0.275, 0.101]}
          />
          <mesh
            name="Cube017"
            geometry={nodes.Cube017.geometry}
            material={materials.plumbing}
            position={[2.991, 4.242, -7.539]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.024, 0.053, 0.057]}
          />
          <mesh
            name="Cube004"
            geometry={nodes.Cube004.geometry}
            material={materials.plumbing}
            position={[-4.203, 4.206, -5]}
            rotation={[Math.PI, 0, Math.PI / 2]}
            scale={[0.024, 0.053, 0.057]}
          />
          <mesh
            name="Floor002"
            geometry={nodes.Floor002.geometry}
            material={materials.floor}
            position={[14.138, 2.727, -19.9]}
          />
          <mesh
            name="Walls002"
            geometry={nodes.Walls002.geometry}
            material={materials['walls 2']}
            position={[15.552, 5.194, -21.678]}
          />
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials.wood2}
            position={[19.571, 5.648, -18.977]}
          />
          <group name="Window004" position={[14.872, 5.801, -24.329]}>
            <mesh name="Cube213" geometry={nodes.Cube213.geometry} material={materials.wood2} />
            <mesh
              name="Cube213_1"
              geometry={nodes.Cube213_1.geometry}
              material={materials.window}
            />
          </group>
          <mesh
            name="Walls004"
            geometry={nodes.Walls004.geometry}
            material={materials['walls 2']}
            position={[23.504, 5.138, -22.812]}
          />
          <mesh
            name="Floor004"
            geometry={nodes.Floor004.geometry}
            material={materials.floor}
            position={[22.725, 2.727, -19.58]}
          />
          <mesh
            name="Walls005"
            geometry={nodes.Walls005.geometry}
            material={materials['walls 2']}
            position={[18.596, 5.157, -9.206]}
          />
          <mesh
            name="Window006"
            geometry={nodes.Window006.geometry}
            material={materials.painting}
            position={[18.042, 5.677, -3.047]}
          />
          <mesh
            name="Floor003"
            geometry={nodes.Floor003.geometry}
            material={materials.floor}
            position={[19.137, 2.727, -8.859]}
          />
          <group
            name="Window012"
            position={[25.358, 5.801, -9.375]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh name="Cube214" geometry={nodes.Cube214.geometry} material={materials.wood2} />
            <mesh
              name="Cube214_1"
              geometry={nodes.Cube214_1.geometry}
              material={materials.window}
            />
          </group>
          <mesh
            name="Cube035"
            geometry={nodes.Cube035.geometry}
            material={materials.wood2}
            position={[8.017, 2.721, -13.695]}
          />
          <mesh
            name="Cube036"
            geometry={nodes.Cube036.geometry}
            material={materials.wood2}
            position={[11.215, 2.721, -6.223]}
          />
          <mesh
            name="Cube038"
            geometry={nodes.Cube038.geometry}
            material={materials.wood2}
            position={[9.804, 3.728, -12.282]}
          />
          <mesh
            name="Cube039"
            geometry={nodes.Cube039.geometry}
            material={materials.wood2}
            position={[5.479, 3.728, -12.284]}
          />
          <mesh
            name="Cube040"
            geometry={nodes.Cube040.geometry}
            material={materials.wood2}
            position={[7.63, 3.728, -12.284]}
          />
          <mesh
            name="Cube041"
            geometry={nodes.Cube041.geometry}
            material={materials.wood2}
            position={[9.804, 3.728, -4.232]}
          />
          <mesh
            name="Cube042"
            geometry={nodes.Cube042.geometry}
            material={materials.wood2}
            position={[9.804, 3.728, -6.894]}
          />
          <mesh
            name="Cube043"
            geometry={nodes.Cube043.geometry}
            material={materials.wood2}
            position={[9.804, 3.728, -9.703]}
          />
          <mesh
            name="Cube045"
            geometry={nodes.Cube045.geometry}
            material={materials.wood2}
            position={[9.806, 4.662, -7.593]}
          />
          <mesh
            name="Walls003"
            geometry={nodes.Walls003.geometry}
            material={materials['walls 2']}
            position={[7.141, 4.876, -15.187]}
          />
          <mesh
            name="Cube058"
            geometry={nodes.Cube058.geometry}
            material={materials.wood2}
            position={[7.645, 4.662, -12.284]}
          />
          <mesh
            name="Plane010"
            geometry={nodes.Plane010.geometry}
            material={materials['walls 2']}
            position={[5.971, 0.099, -13.816]}
          />
          <mesh
            name="Cube057"
            geometry={nodes.Cube057.geometry}
            material={materials.wood2}
            position={[4.54, -0.536, -10.092]}
          />
          <mesh
            name="Plane011"
            geometry={nodes.Plane011.geometry}
            material={materials['walls 2']}
            position={[0.087, 0.217, -6.209]}
          />
          <mesh
            name="Plane012"
            geometry={nodes.Plane012.geometry}
            material={materials['walls 2']}
            position={[11.597, 0.753, -9.665]}
          />
          <mesh
            name="Cube060"
            geometry={nodes.Cube060.geometry}
            material={materials.wood2}
            position={[5.481, 2.149, -9.036]}
          />
          <mesh
            name="Cube044"
            geometry={nodes.Cube044.geometry}
            material={materials.wood2}
            position={[5.479, -1.204, -6.033]}
          />
          <mesh
            name="Cube061"
            geometry={nodes.Cube061.geometry}
            material={materials.wood2}
            position={[5.479, 0.424, -8.101]}
          />
          <mesh
            name="Cube062"
            geometry={nodes.Cube062.geometry}
            material={materials.wood2}
            position={[5.479, 2.186, -10.292]}
          />
          <mesh
            name="Walls006"
            geometry={nodes.Walls006.geometry}
            material={materials['walls 2']}
            position={[15.006, 0.142, -6.759]}
          />
          <mesh
            name="Plane013"
            geometry={nodes.Plane013.geometry}
            material={materials.floor}
            position={[10.159, -2.419, -12.139]}
          />
          <mesh
            name="Plane014"
            geometry={nodes.Plane014.geometry}
            material={materials.floor}
            position={[8.45, 2.494, -11.123]}
          />
          <mesh
            name="Walls007"
            geometry={nodes.Walls007.geometry}
            material={materials['walls 2']}
            position={[6.449, 0.085, -18.445]}
          />
          <mesh
            name="Cube075"
            geometry={nodes.Cube075.geometry}
            material={materials.painting}
            position={[3.566, 4.456, -5.453]}
          />
          <mesh
            name="Cube076"
            geometry={nodes.Cube076.geometry}
            material={materials.painting}
            position={[3.566, 1.334, -7.868]}
          />
          <mesh
            name="Cube077"
            geometry={nodes.Cube077.geometry}
            material={materials.painting}
            position={[3.566, 0.138, -6.602]}
          />
          <mesh
            name="Cube078"
            geometry={nodes.Cube078.geometry}
            material={materials.wood2}
            position={[5.504, 0.617, -15.295]}
          />
          <mesh
            name="Cube113"
            geometry={nodes.Cube113.geometry}
            material={materials['walls 2']}
            position={[9.371, -0.195, -19.622]}
          />
          <mesh
            name="Cube127"
            geometry={nodes.Cube127.geometry}
            material={materials.wood2}
            position={[19.185, 0.854, -14.543]}
            rotation={[Math.PI / 2, 1.485, -Math.PI / 2]}
            scale={[1, 1, 0.749]}
          />
          <mesh
            name="Cube130"
            geometry={nodes.Cube130.geometry}
            material={materials.wood2}
            position={[17.567, -0.649, -19.657]}
            rotation={[0, -0.351, 0]}
            scale={[0.233, 0.584, 0.233]}
          />
          <mesh
            name="Cube128"
            geometry={nodes.Cube128.geometry}
            material={materials.wood2}
            position={[12.474, 0.854, -23.992]}
            rotation={[Math.PI / 2, 1.485, -Math.PI / 2]}
            scale={[1, 1, 0.749]}
          />
          <mesh
            name="Cube129"
            geometry={nodes.Cube129.geometry}
            material={materials.painting}
            position={[3.566, 5.862, -8.85]}
          />
          <mesh
            name="Cube131"
            geometry={nodes.Cube131.geometry}
            material={materials.painting}
            position={[3.566, 2.72, -9.288]}
          />
          <mesh
            name="Cube132"
            geometry={nodes.Cube132.geometry}
            material={materials['walls 2']}
            position={[8.024, 0.665, -2.877]}
            scale={[0.215, 0.215, 0.313]}
          />
          <group name="Window002" position={[-5.294, 1.176, -9.428]} rotation={[0, Math.PI / 2, 0]}>
            <mesh name="Cube216" geometry={nodes.Cube216.geometry} material={materials.wood2} />
            <mesh
              name="Cube216_1"
              geometry={nodes.Cube216_1.geometry}
              material={materials.window}
            />
          </group>
          <group name="Window008" position={[-2.28, 1.176, -24.162]}>
            <mesh name="Cube218" geometry={nodes.Cube218.geometry} material={materials.wood2} />
            <mesh
              name="Cube218_1"
              geometry={nodes.Cube218_1.geometry}
              material={materials.window}
            />
          </group>
          <group name="Window009" position={[18.048, 1.176, -24.162]}>
            <mesh name="Cube219" geometry={nodes.Cube219.geometry} material={materials.wood2} />
            <mesh
              name="Cube219_1"
              geometry={nodes.Cube219_1.geometry}
              material={materials.window}
            />
          </group>
          <group
            name="Window010"
            position={[25.115, 1.176, -20.004]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh name="Cube220" geometry={nodes.Cube220.geometry} material={materials.wood2} />
            <mesh
              name="Cube220_1"
              geometry={nodes.Cube220_1.geometry}
              material={materials.window}
            />
          </group>
          <group
            name="Window011"
            position={[18.472, 1.176, -3.108]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh name="Cube221" geometry={nodes.Cube221.geometry} material={materials.wood2} />
            <mesh
              name="Cube221_1"
              geometry={nodes.Cube221_1.geometry}
              material={materials.window}
            />
          </group>
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.plumbing}
            position={[-4.296, 0.057, -12.186]}
            rotation={[0, -0.489, 0]}
            scale={[0.552, 0.276, 0.552]}
          />
          <mesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials.wood2}
            position={[-3.107, -1.13, -11.566]}
          />
          <mesh
            name="Cube020"
            geometry={nodes.Cube020.geometry}
            material={materials.wood2}
            position={[-1.485, 1.508, -13.722]}
          />
          <mesh
            name="Cube007"
            geometry={nodes.Cube007.geometry}
            material={materials.wood2}
            position={[3.846, -0.01, -13.486]}
            scale={[1, 0.072, 1]}
          />
          <mesh
            name="closet_for_hiding003"
            geometry={nodes.closet_for_hiding003.geometry}
            material={materials['metal 2.001']}
            position={[9.94, -0.115, -10.637]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={1.365}
          />
          <mesh
            name="Plane015"
            geometry={nodes.Plane015.geometry}
            material={materials.ground}
            position={[-14.53, -3.079, -26.435]}
          />
          <mesh
            name="Cube080"
            geometry={nodes.Cube080.geometry}
            material={materials.floor}
            position={[-9.313, -2.617, -19.696]}
          />
          <mesh
            name="Cube079"
            geometry={nodes.Cube079.geometry}
            material={materials['walls 2']}
            position={[-4.985, -2.663, -19.942]}
          />
          <mesh
            name="Plane016"
            geometry={nodes.Plane016.geometry}
            material={materials.wood3}
            position={[-13.063, -0.442, -26.376]}
          />
          <mesh
            name="Cube081"
            geometry={nodes.Cube081.geometry}
            material={materials.walls}
            position={[-15.682, -0.751, -19.907]}
          />
          <mesh
            name="Cube091"
            geometry={nodes.Cube091.geometry}
            material={materials.wood2}
            position={[-9.94, -1.487, -29.369]}
          />
          <mesh
            name="Cube092"
            geometry={nodes.Cube092.geometry}
            material={materials.wood2}
            position={[-18.12, -1.611, -17.624]}
          />
          <mesh
            name="Cube093"
            geometry={nodes.Cube093.geometry}
            material={materials.floor}
            position={[11.648, -5.512, -9.811]}
          />
          <mesh
            name="Cube094"
            geometry={nodes.Cube094.geometry}
            material={materials.floor}
            position={[7.418, -7.387, -12.977]}
          />
          <mesh
            name="Cube095"
            geometry={nodes.Cube095.geometry}
            material={materials.walls}
            position={[6.368, -5.453, -14.419]}
          />
          <mesh
            name="Cube096"
            geometry={nodes.Cube096.geometry}
            material={materials.walls}
            position={[5.857, -4.942, -7.85]}
          />
          <mesh
            name="Cube097"
            geometry={nodes.Cube097.geometry}
            material={materials.wood2}
            position={[5.951, -5.986, -8.447]}
          />
          <mesh
            name="Cube101"
            geometry={nodes.Cube101.geometry}
            material={materials.wood2}
            position={[4.556, -4.911, -14.828]}
          />
          <mesh
            name="Cube103"
            geometry={nodes.Cube103.geometry}
            material={materials.safe}
            position={[0.097, -6.215, -12.266]}
          />
          <mesh
            name="Cube110"
            geometry={nodes.Cube110.geometry}
            material={materials.ground}
            position={[-14.205, -5.862, -18.737]}
          />
          <mesh
            name="Cube111"
            geometry={nodes.Cube111.geometry}
            material={materials.walls}
            position={[-4.586, -6.062, -17.699]}
          />
          <mesh
            name="Cube105"
            geometry={nodes.Cube105.geometry}
            material={materials.ground}
            position={[-11.273, -5.861, -18.722]}
          />
          <mesh
            name="Cube112"
            geometry={nodes.Cube112.geometry}
            material={materials.ground}
            position={[-8.642, -3.87, -18.737]}
          />
          <mesh
            name="Floor005"
            geometry={nodes.Floor005.geometry}
            material={materials.floor}
            position={[21.844, 2.727, -29.032]}
          />
          <mesh
            name="Walls008"
            geometry={nodes.Walls008.geometry}
            material={materials['walls 2']}
            position={[21.824, 5.309, -29.038]}
          />
          <mesh
            name="Cube114"
            geometry={nodes.Cube114.geometry}
            material={materials.wood}
            position={[20.405, 1.35, -34.844]}
          />
          <mesh
            name="Walls010"
            geometry={nodes.Walls010.geometry}
            material={materials['walls 2']}
            position={[20.528, 3.626, -34.286]}
          />
          <mesh
            name="Plane018"
            geometry={nodes.Plane018.geometry}
            material={materials['walls 2']}
            position={[18.282, 6.186, -34.91]}
          />
          <mesh
            name="Walls009"
            geometry={nodes.Walls009.geometry}
            material={materials['walls 2']}
            position={[11.233, 2.798, -34.411]}
          />
          <mesh
            name="Cube037"
            geometry={nodes.Cube037.geometry}
            material={materials.floor}
            position={[8.545, -2.722, -37.554]}
          />
          <mesh
            name="Cube115"
            geometry={nodes.Cube115.geometry}
            material={materials.floor}
            position={[9.251, 0.527, -35.495]}
          />
          <mesh
            name="Cube116"
            geometry={nodes.Cube116.geometry}
            material={materials['walls 2']}
            position={[12.762, 2.471, -29.96]}
          />
          <mesh
            name="Cube117"
            geometry={nodes.Cube117.geometry}
            material={materials.wood2}
            position={[11.589, 2.448, -37.556]}
          />
          <mesh
            name="Cube118"
            geometry={nodes.Cube118.geometry}
            material={materials.wood2}
            position={[8.736, 2.448, -36.357]}
          />
          <mesh
            name="Cube121"
            geometry={nodes.Cube121.geometry}
            material={materials.wood2}
            position={[11.589, 1.515, -36.366]}
          />
          <mesh
            name="Cube119"
            geometry={nodes.Cube119.geometry}
            material={materials.wood2}
            position={[8.991, 1.515, -36.366]}
          />
          <mesh
            name="Cube120"
            geometry={nodes.Cube120.geometry}
            material={materials.wood2}
            position={[6.097, 1.515, -36.366]}
          />
          <group name="Walls011" position={[12.141, -2.759, -32.796]}>
            <mesh
              name="Cube174"
              geometry={nodes.Cube174.geometry}
              material={materials['walls 2']}
            />
            <mesh name="Cube174_1" geometry={nodes.Cube174_1.geometry} material={materials.floor} />
          </group>
          <mesh
            name="Cube122"
            geometry={nodes.Cube122.geometry}
            material={materials.floor}
            position={[6.806, -6.239, -30.203]}
          />
          <mesh
            name="Cube123"
            geometry={nodes.Cube123.geometry}
            material={materials['walls 2']}
            position={[11.655, -7.271, -26.958]}
          />
          <mesh
            name="Cube124"
            geometry={nodes.Cube124.geometry}
            material={materials.walls}
            position={[10.563, -5.118, -24.416]}
          />
          <mesh
            name="Cube125"
            geometry={nodes.Cube125.geometry}
            material={materials.walls}
            position={[11.933, -2.449, -28.203]}
          />
          <mesh
            name="Cube126"
            geometry={nodes.Cube126.geometry}
            material={materials.walls}
            position={[11.656, -2.933, -24.457]}
          />
          <mesh
            name="Cube008"
            geometry={nodes.Cube008.geometry}
            material={materials.wood2}
            position={[14.687, 1.97, -30.28]}
            scale={[1, 0.072, 1]}
          />
          <mesh
            name="Cube011"
            geometry={nodes.Cube011.geometry}
            material={nodes.Cube011.material}
            position={[18.493, -2.708, -37.67]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 0.072, 1]}
          />
          <group name="bed001" position={[-6.997, 3.456, -18.061]}>
            <mesh name="Cube243" geometry={nodes.Cube243.geometry} material={materials.wood2} />
            <mesh name="Cube243_1" geometry={nodes.Cube243_1.geometry} material={materials.bed} />
            <mesh
              name="Cube243_2"
              geometry={nodes.Cube243_2.geometry}
              material={materials['bed 2']}
            />
          </group>
          <mesh
            name="closet_for_hiding001"
            geometry={nodes.closet_for_hiding001.geometry}
            material={materials['metal 2']}
            position={[5.825, 4.863, -23.809]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.365}
          />
          <Door
        doorId="nightstand_box002"
        geometry={nodes.Cube255.geometry}
        material={materials.wood2}
        position={[-1.69, 4.801, -23.407]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube255_1.geometry} material={materials.metal} />
      </Door>
      <mesh name="nightstand001" geometry={nodes.nightstand001.geometry} material={materials.wood2} position={[-2.769, 4.136, -23.863]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.028, 0.797]} />
            <mesh name="nightstand002" geometry={nodes.nightstand002.geometry} material={materials['wood2.012']} position={[6.886, 1.969, -32.08]} rotation={[0, 1.571, 0]} scale={[1, 0.028, 0.797]} />
      <mesh name="nightstand003" geometry={nodes.nightstand003.geometry} material={materials['wood2.010']} position={[13.418, 4.133, -8.947]} scale={[1, 0.028, 0.797]} />
      <mesh name="nightstand004" geometry={nodes.nightstand004.geometry} material={materials['wood2.016']} position={[-5.852, -0.807, -23.645]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.028, 0.797]} />
      <mesh name="nightstand006" geometry={nodes.nightstand006.geometry} material={materials['wood2.014']} position={[23.866, -0.81, -5.525]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 0.028, 0.797]} />
      <mesh name="nightstand007" geometry={nodes.nightstand007.geometry} material={materials['wood2.006']} position={[24.74, 4.133, -17.603]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 0.028, 0.797]} />
      <mesh name="nightstand008" geometry={nodes.nightstand008.geometry} material={materials['wood2.008']} position={[15.026, 4.133, -15.904]} rotation={[0, 1.571, 0]} scale={[1, 0.028, 0.797]} />
      <mesh name="nightstand009" geometry={nodes.nightstand009.geometry} material={materials['wood2.004']} position={[13.205, 9.205, -18.301]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 0.028, 0.797]} />
      <Door
        doorId="nightstand_box001"
        geometry={nodes.Cube053_1.geometry}
        material={materials['wood2.009']}
        position={[16.106, 4.797, -16.36]}
        rotation={[Math.PI, -1.571, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube053_2.geometry} material={materials['metal.007']} />
      </Door>
      <Door
        doorId="nightstand_box003"
        geometry={nodes.Cube015.geometry}
        material={materials['wood2.003']}
        position={[-3.849, 4.801, -23.407]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['metal.002']} />
      </Door>
      <Door
        doorId="nightstand_box004"
        geometry={nodes.Cube057_1.geometry}
        material={materials['wood2.011']}
        position={[13.874, 4.797, -7.867]}
        rotation={[Math.PI, 0, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube057_2.geometry} material={materials['metal.009']} />
      </Door>
      <Door
        doorId="nightstand_box005"
        geometry={nodes.Cube059.geometry}
        material={materials['wood2.010']}
        position={[13.874, 4.797, -10.027]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube059_1.geometry} material={materials['metal.010']} />
      </Door>
      <Door
        doorId="nightstand_box006"
        geometry={nodes.Cube055.geometry}
        material={materials['wood2.008']}
        position={[13.947, 4.797, -16.36]}
        rotation={[0, 1.571, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube055_1.geometry} material={materials['metal.008']} />
      </Door>
      <Door
        doorId="nightstand_box007"
        geometry={nodes.Cube068.geometry}
        material={materials['wood2.013']}
        position={[7.966, 2.633, -32.536]}
        rotation={[Math.PI, -1.571, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube068_1.geometry} material={materials['metal.011']} />
      </Door>
      <Door
        doorId="nightstand_box008"
        geometry={nodes.Cube075_1.geometry}
        material={materials['wood2.015']}
        position={[23.409, -0.145, -6.605]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube075_2.geometry} material={materials['metal.013']} />
      </Door>
      <Door
        doorId="nightstand_box009"
        geometry={nodes.Cube077_1.geometry}
        material={materials['wood2.014']}
        position={[23.409, -0.145, -4.446]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube077_2.geometry} material={materials['metal.014']} />
      </Door>
      <Door
        doorId="nightstand_box010"
        geometry={nodes.Cube079_1.geometry}
        material={materials['wood2.017']}
        position={[-6.932, -0.143, -23.189]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube079_2.geometry} material={materials['metal.015']} />
      </Door>
      <Door
        doorId="nightstand_box011"
        geometry={nodes.Cube080_1.geometry}
        material={materials['wood2.016']}
        position={[-4.772, -0.143, -23.189]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube080_2.geometry} material={materials['metal.016']} />
      </Door>
      <Door
        doorId="nightstand_box012"
        geometry={nodes.Cube070.geometry}
        material={materials['wood2.012']}
        position={[5.806, 2.633, -32.536]}
        rotation={[0, 1.571, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube070_1.geometry} material={materials['metal.012']} />
      </Door>
      <Door
        doorId="nightstand_box014"
        geometry={nodes.Cube041_1.geometry}
        material={materials['wood2.006']}
        position={[24.283, 4.797, -16.523]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube041_2.geometry} material={materials['metal.005']} />
      </Door>
      <Door
        doorId="nightstand_box015"
        geometry={nodes.Cube045_1.geometry}
        material={materials['wood2.007']}
        position={[24.283, 4.797, -18.683]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={-1}
      >
        <mesh geometry={nodes.Cube045_2.geometry} material={materials['metal.006']} />
      </Door>
      <Door
        doorId="nightstand_box017"
        geometry={nodes.Cube037_1.geometry}
        material={materials['wood2.005']}
        position={[12.125, 9.869, -17.845]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['metal.003']} />
      </Door>
      <Door
        doorId="nightstand_box018"
        geometry={nodes.Cube039_1.geometry}
        material={materials['wood2.004']}
        position={[14.285, 9.869, -17.845]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.03, 0.037, 0.127]}
        openDirection={1}
      >
        <mesh geometry={nodes.Cube039_2.geometry} material={materials['metal.004']} />
      </Door>

          <mesh
            name="table001"
            geometry={nodes.table001.geometry}
            material={materials.wood2}
            position={[-0.747, 3.742, -16.362]}
          />
          <mesh
            name="closet_for_hiding002"
            geometry={nodes.closet_for_hiding002.geometry}
            material={materials['metal 2']}
            position={[-5.1, 4.867, -12.658]}
            scale={1.365}
          />
          <mesh
            name="closet001"
            geometry={nodes.closet001.geometry}
            material={materials.wood2}
            position={[24.866, 4.933, -12.901]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[1, 0.037, 1]}
          />
          <group name="bed002" position={[22.683, 3.456, -4.829]} rotation={[0, Math.PI / 2, 0]}>
            <mesh name="Cube266" geometry={nodes.Cube266.geometry} material={materials.wood2} />
            <mesh name="Cube266_1" geometry={nodes.Cube266_1.geometry} material={materials.bed} />
            <mesh
              name="Cube266_2"
              geometry={nodes.Cube266_2.geometry}
              material={materials['bed 2']}
            />
          </group>
          <mesh name="table002" geometry={nodes.table002.geometry} material={materials.wood2} position={[18.694, 3.743, -13.758]} />
          <mesh name="table004" geometry={nodes.table004.geometry} material={materials.wood2} position={[20.952, -1.224, -13.71]} />

          <group name="bed003" position={[11.064, 3.456, -22.577]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh name="Cube272" geometry={nodes.Cube272.geometry} material={materials.wood2} />
            <mesh name="Cube272_1" geometry={nodes.Cube272_1.geometry} material={materials.bed} />
            <mesh
              name="Cube272_2"
              geometry={nodes.Cube272_2.geometry}
              material={materials['bed 2']}
            />
          </group>



          <group name="well001" position={[-16.204, -2.538, -30.298]} rotation={[0, -0.617, 0]}>
            <mesh name="Cone002" geometry={nodes.Cone002.geometry} material={materials.well} />
            <mesh name="Cone002_1" geometry={nodes.Cone002_1.geometry} material={materials.wood2} />
          </group>
          <group name="shaft001" position={[-16.196, -1.079, -30.3]} rotation={[0, -0.619, 0]}>
            <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials.wood2} />
            <mesh name="Cylinder024_1" geometry={nodes.Cylinder024_1.geometry} material={materials.rope} />
          </group>
          <mesh
            name="rope001"
            geometry={nodes.rope001.geometry}
            material={materials.rope}
            position={[-16.202, -3.8 + bucketHeight / 2, -30.295]}
            scale={[1, Math.max(0.1, 1 - bucketHeight / 5.5), 1]}
          />
          {handleSet && (
            <mesh
              name="handle001"
              geometry={nodes.handle001.geometry}
              material={materials.wood2}
              position={[-14.702, -1.079, -30.3]}
              rotation={[handleRotation, -0.615, 0]}
            />
          )}
          <RigidBody
            ref={bucketRef}
            type="kinematicPosition"
            position={[-16.202, -6.604 + bucketHeight, -30.295]}
            rotation={[0, 0.396, 0]}
            colliders="trimesh"
            friction={1.0}
          >
            <mesh
              name="bucket001"
              geometry={nodes.bucket001.geometry}
              material={materials.metal}
              scale={[0.545, 0.461, 0.545]}
            />
          </RigidBody>
          <mesh
            ref={bladeRef}
            name="blade001"
            geometry={nodes.blade001.geometry}
            material={materials.vase}
            position={[-10.675, bladePosition, -28.671]}
            scale={0.885}
          />
          {/* Watermelon in guillotine - visible when placed but before blade cuts it */}
          {watermelonPlaced && !itemRevealed && (
            <group
              name="watermelon_in_guillotine"
              position={[-10.72, -1.6, -28.6]}
              rotation={[30, 50, 40]} // Convert Blender rotation to radians
              scale={[0.308, 0.427, 0.308]}
            >
              <mesh
                geometry={itemsModel.nodes.Sphere001.geometry}
                material={itemsModel.materials.watermelon_green}
              />
              <mesh
                geometry={itemsModel.nodes.Sphere001_1.geometry}
                material={itemsModel.materials.watermelon_black}
              />
            </group>
          )}
          <mesh
            name="closet002"
            geometry={nodes.closet002.geometry}
            material={materials.wood2}
            position={[-4.792, -0.035, -4.345]}
            scale={[1, 0.037, 1]}
          />
          <mesh
            name="table003"
            geometry={nodes.table003.geometry}
            material={materials.wood2}
            position={[-0.034, -1.212, -7.651]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="closet003"
            geometry={nodes.closet003.geometry}
            material={materials.wood2}
            position={[13.6, -0.04, -9.046]}
            scale={[1, 0.037, 1]}
          />
          <mesh
            name="closet004"
            geometry={nodes.closet004.geometry}
            material={materials.wood2}
            position={[-4.487, -0.04, -15.609]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 0.037, 1]}
          />
          <mesh
            name="closet005"
            geometry={nodes.closet005.geometry}
            material={materials.wood2}
            position={[4.116, -0.04, -23.681]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 0.037, 1]}
          />
          <mesh
            name="table005"
            geometry={nodes.table005.geometry}
            material={materials.wood2}
            position={[-4.473, -6.615, -15.521]}
            scale={0.622}
          />
          <mesh
            name="table006"
            geometry={nodes.table006.geometry}
            material={materials.wood2}
            position={[20.181, 3.756, -28.601]}
            rotation={[0, Math.PI / 2, 0]}
          />


          {/* Shield 1 - Only render if active */}
          {activeShieldId === 1 && (
            <>
              <mesh
                name="shield"
                geometry={nodes.shield.geometry}
                material={materials.shield}
                position={[6.413, -4.602, -4.425]}
              />
              {!shieldWireCut && (
                <mesh
                  name="shield_wire"
                  geometry={nodes.shield_wire.geometry}
                  material={materials.wire}
                  position={[6.412, -4.596, -4.436]}
                />
              )}
              {shieldWireCut && (
                <mesh
                  name="shield_wire_cut"
                  geometry={nodes.shield_wire_cut.geometry}
                  material={materials.wire}
                  position={[6.412, -4.596, -4.436]}
                />
              )}
            </>
          )}
          
          {/* Shield 2 - Only render if active */}
          {activeShieldId === 2 && (
            <>
              <mesh
                name="shield002"
                geometry={nodes.shield002.geometry}
                material={materials['shield.002']}
                position={[3.001, 10.944, -16.725]}
                rotation={[Math.PI, 0, Math.PI]}
              />
              {!shieldWireCut && (
                <mesh
                  name="shield_wire002"
                  geometry={nodes.shield_wire002.geometry}
                  material={materials['wire.002']}
                  position={[3.002, 10.95, -16.713]}
                  rotation={[Math.PI, 0, Math.PI]}
                />
              )}
              {shieldWireCut && (
                <mesh
                  name="shield_wire_cut002"
                  geometry={nodes.shield_wire_cut002.geometry}
                  material={materials['wire.002']}
                  position={[3.002, 10.95, -16.713]}
                  rotation={[Math.PI, 0, Math.PI]}
                />
              )}
            </>
          )}
          
          {/* Shield 3 - Only render if active */}
          {activeShieldId === 3 && (
            <>
              <mesh
                name="shield003"
                geometry={nodes.shield003.geometry}
                material={materials['shield.003']}
                position={[-17.17, -0.065, -16.596]}
              />
              {!shieldWireCut && (
                <mesh
                  name="shield_wire003"
                  geometry={nodes.shield_wire003.geometry}
                  material={materials['wire.003']}
                  position={[-17.171, -0.059, -16.608]}
                />
              )}
              {shieldWireCut && (
                <mesh
                  name="shield_wire_cut003"
                  geometry={nodes.shield_wire_cut003.geometry}
                  material={materials['wire.003']}
                  position={[-17.171, -0.059, -16.608]}
                />
              )}
            </>
          )}



          <mesh
            name="cut_indicators"
            geometry={nodes.cut_indicators.geometry}
            material={materials.well}
            position={[6.131, 0.25, -2.917]}
            scale={[0.122, 0.257, 0.122]}
          />
          <mesh
            name="cut_indicator_1"
            geometry={nodes.cut_indicator_1.geometry}
            position={[6.131, 0.145, -3.018]}
            scale={0.075}
          >
            <meshStandardMaterial 
              color={wiresCut >= 1 ? '#00ff00' : '#ff0000'} 
              emissive={wiresCut >= 1 ? '#00ff00' : '#ff0000'}
              emissiveIntensity={1}
            />
          </mesh>
          <mesh
            name="cut_indicator_2"
            geometry={nodes.cut_indicator_2.geometry}
            position={[6.131, 0.349, -3.018]}
            scale={0.075}
          >
            <meshStandardMaterial 
              color={wiresCut >= 2 ? '#00ff00' : '#ff0000'} 
              emissive={wiresCut >= 2 ? '#00ff00' : '#ff0000'}
              emissiveIntensity={1}
            />
          </mesh>
          {!doorWireCut && (
            <mesh
              name="door_wire"
              geometry={nodes.door_wire.geometry}
              material={materials.wire}
              position={[6.131, 0.574, -2.979]}
              scale={[0.026, 0.1, 0.034]}
            />
          )}
          {/* Wood plank on main door - no physics when attached */}
          {!isChippedOff && (
            <mesh
              name="wood_plank"
              geometry={nodes.wood_plank.geometry}
              material={materials.wood2}
              position={[8.036, -0.873, -3.118]}
              rotation={[Math.PI / 2, -0.236, 0]}
              scale={[0.273, 0.025, 0.273]}
            />
          )}
          {!plankPlaced && (
            <mesh 
              name="wood_plank_slot" 
              geometry={nodes.wood_plank001.geometry} 
              material={materials.wood2} 
              position={[8.106, 7.94, -8.589]} 
              rotation={[-Math.PI, 0, 0]} 
              scale={[0.8, 0.3, 0.8]} 
              visible={false}
            />
          )}
          {!lockOpened && (
            <group name="door_lock" position={[6.996, 0.675, -3.215]} scale={[0.366, 0.099, 0.037]}>
              <mesh name="Cube038_1" geometry={nodes.Cube038_1.geometry} material={materials.wood2} />
              <mesh name="Cube038_2" geometry={nodes.Cube038_2.geometry} material={materials.metal} />
              <mesh
                name="Cube038_3"
                geometry={nodes.Cube038_3.geometry}
                material={materials['metal 2']}
              />
            </group>
          )}
          <mesh
            name="terminal"
            geometry={nodes.terminal.geometry}
            material={materials.well}
            position={[10.066, 0.37, -2.941]}
            scale={[0.264, 0.532, 0.219]}
          />
          <mesh
            name="terminal_indicator"
            geometry={nodes.terminal_indicator.geometry}
            position={[9.875, 0.573, -3.066]}
            scale={0.056}
          >
            <meshStandardMaterial 
              color={cardSwiped ? '#00ff00' : '#ff0000'} 
              emissive={cardSwiped ? '#00ff00' : '#ff0000'}
              emissiveIntensity={1}
            />
          </mesh>
          {doorWireCut && (
            <mesh
              name="door_wire_cut"
              geometry={nodes.door_wire_cut.geometry}
              material={materials.wire}
              position={[6.131, 0.574, -2.979]}
              scale={[0.026, 0.1, 0.034]}
            />
          )}
          <mesh
            name="black_wall"
            geometry={nodes.black_wall.geometry}
            material={materials.black}
            position={[0.486, 4.832, -33.622]}
            scale={[0.221, 14.826, 8.85]}
          />
          <mesh
            name="black_wall_2"
            geometry={nodes.black_wall_2.geometry}
            material={materials.black}
            position={[-17.809, 4.832, -15.134]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.221, 14.826, 8.85]}
          />
          <mesh
            name="black_wall_3"
            geometry={nodes.black_wall_3.geometry}
            material={materials['black.001']}
            position={[-3.967, 15.743, -19.427]}
            rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
            scale={[0.221, 14.826, 8.85]}
          />
        </group>
      </RigidBody>

      {/* Items placed on table001 */}
      <Items />
      
      {/* Wood plank placed on attic hole - with collision */}
      {plankPlaced && (
        <RigidBody
          position={[8.106, 7.94, -8.589]}
          rotation={[-Math.PI, 0, 0]}
          type="fixed"
          colliders="cuboid"
        >
          <mesh 
            name="wood_plank001" 
            geometry={nodes.wood_plank001.geometry} 
            material={materials.wood2} 
            scale={[0.273, 0.025, 0.273]} 
          />
        </RigidBody>
      )}
      
      {/* Attic planks with physics */}
      <AtticPlanks nodes={nodes} materials={materials} />
      
      {/* Boxes with physics */}
      <RigidBody
        position={[22.352, 3.464, -23.834]}
        type="dynamic"
        colliders="cuboid"
        onCollisionEnter={() => playBoxSound(box1LastSound)}
      >
        <mesh
          name="box001"
          geometry={nodes.box001.geometry}
          material={materials.box}
        />
      </RigidBody>
      
      <RigidBody
        position={[22.352, 4.725, -23.834]}
        type="dynamic"
        colliders="cuboid"
        onCollisionEnter={() => playBoxSound(box2LastSound)}
      >
        <mesh
          name="box002"
          geometry={nodes.box002.geometry}
          material={materials.box}
        />
      </RigidBody>
      
      <RigidBody
        position={[22.352, 5.989, -23.834]}
        type="dynamic"
        colliders="cuboid"
        onCollisionEnter={() => playBoxSound(box3LastSound)}
      >
        <mesh
          name="box003"
          geometry={nodes.box003.geometry}
          material={materials.box}
        />
      </RigidBody>
      
      {/* Hatch with physics - falls when stepped on */}
      {hatchVisible && (
        <RigidBody
          ref={hatchRef}
          position={[-2.784, 7.832, -12.5]}
          type={hatchFallen ? "dynamic" : "fixed"}
          colliders="cuboid"
          mass={20}
          gravityScale={1}
          linearDamping={0.3}
          angularDamping={0.3}
          onCollisionEnter={(e) => {
            if (!hatchFallen && e.other.rigidBodyObject?.name === 'player') {
              const audio = new Audio('/sounds/metal.mp3');
              audio.volume = (volume / 100) * 0.5;
              audio.play().catch(err => console.warn('Metal sound play failed:', err));
              setHatchFallen(true);
            }
          }}
        >
          <mesh
            name="hatch001"
            geometry={nodes.hatch001.geometry}
            material={materials['metal 2']}
          />
        </RigidBody>
      )}
      
      {/* Planks with physics */}
      <RigidBody
        position={[-1.02, 8.885, -12.485]}
        rotation={[0, Math.PI / 2, 0]}
        type="dynamic"
        colliders="hull"
        mass={15}
        gravityScale={1}
        linearDamping={0.5}
        angularDamping={0.5}
        onCollisionEnter={() => playPlankSound(plank1LastSound)}
      >
        <mesh
          name="plank001"
          geometry={nodes.plank001.geometry}
          material={materials.wood2}
        />
      </RigidBody>
      
      <RigidBody
        position={[11.714, -6.194, -17.935]}
        type="dynamic"
        colliders="hull"
        mass={15}
        gravityScale={1}
        linearDamping={0.5}
        angularDamping={0.5}
        onCollisionEnter={() => playPlankSound(plank2LastSound)}
      >
        <mesh
          name="plank002"
          geometry={nodes.plank002.geometry}
          material={materials.wood2}
        />
      </RigidBody>
      
      {/* Vase table with physics */}
      <RigidBody
        position={[1.791, 4.087, -21.712]}
        type="dynamic"
        colliders="cuboid"
        mass={2}
        gravityScale={1}
        linearDamping={0.5}
        angularDamping={0.5}
      >
        <mesh
          name="vase_table001"
          geometry={nodes.vase_table001.geometry}
          material={materials.wood2}
          scale={[0.099, 0.518, 0.099]}
        />
      </RigidBody>
      
      {/* Lamp with physics */}
      <RigidBody
        position={[9.185, 4.362, -18.753]}
        type="dynamic"
        colliders="hull"
        mass={3}
        gravityScale={1}
        linearDamping={0.5}
        angularDamping={0.5}
      >
        <group name="lamp001">
          <mesh
            name="Cylinder023"
            geometry={nodes.Cylinder023.geometry}
            material={materials.lamp}
          />
          <mesh
            name="Cylinder023_1"
            geometry={nodes.Cylinder023_1.geometry}
            material={materials.lamp2}
          />
        </group>
      </RigidBody>
      
      {/* Chairs */}
      <RigidBody position={[18.692, 3.788, -12.527]} type="fixed" colliders="hull">
        <mesh
          name="chair001"
          geometry={nodes.chair001.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      <RigidBody position={[20.877, -1.174, -12.329]} type="fixed" colliders="hull">
        <mesh
          name="chair002"
          geometry={nodes.chair002.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      <RigidBody position={[15.722, -1.174, -17.182]} rotation={[0, -0.198, 0]} type="fixed" colliders="hull">
        <mesh
          name="chair003"
          geometry={nodes.chair003.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      <RigidBody position={[19.63, -1.174, -17.182]} rotation={[0, 0.29, 0]} type="fixed" colliders="hull">
        <mesh
          name="chair004"
          geometry={nodes.chair004.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      <RigidBody position={[22.904, -1.174, -19.653]} rotation={[-Math.PI, 1.565, -Math.PI]} type="fixed" colliders="hull">
        <mesh
          name="chair005"
          geometry={nodes.chair005.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      <RigidBody position={[19.63, -1.174, -22.073]} rotation={[-Math.PI, 0.269, -Math.PI]} type="fixed" colliders="hull">
        <mesh
          name="chair006"
          geometry={nodes.chair006.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      <RigidBody position={[15.89, -1.174, -22.125]} rotation={[Math.PI, -0.112, Math.PI]} type="fixed" colliders="hull">
        <mesh
          name="chair007"
          geometry={nodes.chair007.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      <RigidBody position={[12.085, -1.174, -19.615]} rotation={[0, -1.57, 0]} type="fixed" colliders="hull">
        <mesh
          name="chair008"
          geometry={nodes.chair008.geometry}
          material={materials.wood2}
          scale={[1, 0.612, 1]}
        />
      </RigidBody>
      
      {/* Attic trigger - sensor that triggers day transition when player falls through */}
      <RigidBody
        position={[8.114, 6.936, -8.506]}
        type="fixed"
        sensor
        colliders={false}
        onIntersectionEnter={(e) => {
          console.log('Attic trigger hit by:', e.other.rigidBodyObject?.name);
          if (e.other.rigidBodyObject?.name === 'player' && e.other.rigidBody) {
            console.log('Player fell through attic trigger!');
            handleAtticTrigger(e.other.rigidBody);
          }
        }}
      >
        <CuboidCollider args={[2, 0.5, 2]} sensor />
        <mesh
          geometry={nodes.attic_trigger.geometry}
          scale={[1.47, 0.043, 1.47]}
          visible={false}
        />
      </RigidBody>
    </>
  );
}

useGLTF.preload('/models/hauntedHouse.glb');
