/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/items.glb --types --keepnames -o src/components/Items.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    handle: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere001_1: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube052_1: THREE.Mesh;
  };
  materials: {
    metal: THREE.MeshStandardMaterial;
    padlock_key: THREE.MeshStandardMaterial;
    master_key: THREE.MeshStandardMaterial;
    vase: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    safe_key: THREE.MeshStandardMaterial;
    wood2: THREE.MeshStandardMaterial;
    watermelon_green: THREE.MeshStandardMaterial;
    watermelon_black: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/items.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="padlock_key" position={[-32.494, 3.712, -1]} scale={[0.054, 0.014, 0.042]}>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.metal} />
        <mesh
          name="Cube002_1"
          geometry={nodes.Cube002_1.geometry}
          material={materials.padlock_key}
        />
      </group>
      <group name="master_key" position={[-32.494, 3.712, -1.237]} scale={[0.054, 0.014, 0.042]}>
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.metal} />
        <mesh
          name="Cube003_1"
          geometry={nodes.Cube003_1.geometry}
          material={materials.master_key}
        />
      </group>
      <group name="card" position={[-31.094, 4.549, -1.511]} scale={[0.145, 0.007, 0.06]}>
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.vase} />
        <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.black} />
      </group>
      <group name="safe_key" position={[-32.494, 3.712, -1.597]} scale={[0.054, 0.014, 0.042]}>
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.metal} />
        <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials.safe_key} />
      </group>
      <mesh
        name="handle"
        geometry={nodes.handle.geometry}
        material={materials.wood2}
        position={[-31.146, 4.548, -2.027]}
      />
      <group
        name="watermelon"
        position={[-30.856, 4.175, -0.522]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={[0.308, 0.427, 0.308]}
      >
        <mesh
          name="Sphere001"
          geometry={nodes.Sphere001.geometry}
          material={materials.watermelon_green}
        />
        <mesh
          name="Sphere001_1"
          geometry={nodes.Sphere001_1.geometry}
          material={materials.watermelon_black}
        />
      </group>
      <group
        name="cut"
        position={[-30.185, 4.064, -1.667]}
        rotation={[-Math.PI, -0.268, 0]}
        scale={[0.017, 0.008, 0.024]}
      >
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.metal} />
        <mesh
          name="Cube024_1"
          geometry={nodes.Cube024_1.geometry}
          material={materials.watermelon_green}
        />
      </group>
      <group
        name="hammer"
        position={[-31.461, 4.302, -0.994]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.181, 0.024, 0.035]}
      >
        <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials.wood2} />
        <mesh name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials.metal} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/items.glb');
