/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/items.glb --types --keepnames -o src/components/Items.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import { RigidBody } from '@react-three/rapier';
import React from 'react';
import { useItems } from '../store/useItems';
import { usePlank } from '../store/usePlank';
import { useGLTF as useHouseGLTF } from '@react-three/drei';

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    handle: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere001_1: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube052_1: THREE.Mesh;
  };
  materials: {
    metal: THREE.MeshStandardMaterial;
    padlock_key: THREE.MeshStandardMaterial;
    master_key: THREE.MeshStandardMaterial;
    vase: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    safe_key: THREE.MeshStandardMaterial;
    wood2: THREE.MeshStandardMaterial;
    watermelon_green: THREE.MeshStandardMaterial;
    watermelon_black: THREE.MeshStandardMaterial;
  };
};

export function Items(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/items.glb') as unknown as GLTFResult;
  const houseModel = useHouseGLTF('/models/hauntedHouse.glb') as any;
  const { isItemHeld, getItemPosition, itemSlots, setSpawnPosition } = useItems();
  const { isChippedOff } = usePlank();
  const [initialized, setInitialized] = React.useState(false);

  // Initialize spawn positions from GLTF empties
  React.useEffect(() => {
    if (!initialized && houseModel?.nodes) {
      Object.entries(itemSlots).forEach(([itemName, slotName]) => {
        const empty = houseModel.nodes[slotName];
        if (empty?.position) {
          const pos: [number, number, number] = [
            empty.position.x,
            empty.position.y,
            empty.position.z,
          ];
          setSpawnPosition(itemName, pos);
        } else {
          console.warn(`Empty ${slotName} not found for item ${itemName}`);
        }
      });
      setInitialized(true);
    }
  }, [houseModel, itemSlots, setSpawnPosition, initialized]);

  // Collision groups:
  // - Group 0 (0x0001): Static geometry (floors, walls, furniture)
  // - Group 1 (0x0002): Player
  // - Group 2 (0x0004): Items
  // Format: (filterMask << 16) | membershipGroup
  // Items belong to group 2 and collide with groups 0 and 2 (not player)
  const itemCollisionGroup = (0x0005 << 16) | 0x0004; // Collides with 0x0001 | 0x0004 = 0x0005

  return (
    <group {...props} dispose={null}>
      {/* Padlock Key - small key with CCD */}
      {!isItemHeld('padlock_key') && (
        <RigidBody
          key={`padlock_key-${getItemPosition('padlock_key', [-1.744, 4.512, -16.36]).join(',')}`}
          type="dynamic"
          position={getItemPosition('padlock_key', [-1.744, 4.512, -16.36])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8} // Slightly smaller collider
        >
          <group name="padlock_key" position={[0, 0, 0]} scale={[0.054, 0.014, 0.042]}>
            <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.metal} />
            <mesh
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials.padlock_key}
            />
          </group>
        </RigidBody>
      )}

      {/* Master Key - small key with CCD */}
      {!isItemHeld('master_key') && (
        <RigidBody
          key={`master_key-${getItemPosition('master_key', [-1.744, 4.512, -16.597]).join(',')}`}
          type="dynamic"
          position={getItemPosition('master_key', [-1.744, 4.512, -16.597])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group name="master_key" position={[0, 0, 0]} scale={[0.054, 0.014, 0.042]}>
            <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.metal} />
            <mesh
              name="Cube003_1"
              geometry={nodes.Cube003_1.geometry}
              material={materials.master_key}
            />
          </group>
        </RigidBody>
      )}

      {/* Card - thin flat object with CCD */}
      {!isItemHeld('card') && (
        <RigidBody
          key={`card-${getItemPosition('card', [-0.344, 5.349, -16.871]).join(',')}`}
          type="dynamic"
          position={getItemPosition('card', [-0.344, 5.349, -16.871])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group name="card" position={[0, 0, 0]} scale={[0.145, 0.007, 0.06]}>
            <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.vase} />
            <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.black} />
          </group>
        </RigidBody>
      )}

      {/* Safe Key - small key with CCD */}
      {!isItemHeld('safe_key') && (
        <RigidBody
          key={`safe_key-${getItemPosition('safe_key', [-1.744, 4.512, -16.957]).join(',')}`}
          type="dynamic"
          position={getItemPosition('safe_key', [-1.744, 4.512, -16.957])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group name="safe_key" position={[0, 0, 0]} scale={[0.054, 0.014, 0.042]}>
            <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.metal} />
            <mesh
              name="Cube010_1"
              geometry={nodes.Cube010_1.geometry}
              material={materials.safe_key}
            />
          </group>
        </RigidBody>
      )}

      {/* Handle - cylindrical object */}
      {!isItemHeld('handle') && (
        <RigidBody
          key={`handle-${getItemPosition('handle', [-0.396, 5.348, -17.387]).join(',')}`}
          type="dynamic"
          position={getItemPosition('handle', [-0.396, 5.348, -17.387])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.85}
        >
          <mesh
            name="handle"
            geometry={nodes.handle.geometry}
            material={materials.wood2}
            position={[0, 0, 0]}
          />
        </RigidBody>
      )}

      {/* Watermelon - round object, use ball collider */}
      {!isItemHeld('watermelon') && (
        <RigidBody
          key={`watermelon-${getItemPosition('watermelon', [-0.106, 4.975, -15.882]).join(',')}`}
          type="dynamic"
          position={getItemPosition('watermelon', [-0.106, 4.975, -15.882])}
          colliders="ball"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.9}
        >
          <group
            name="watermelon"
            position={[0, 0, 0]}
            rotation={[-Math.PI / 2, 1.57, 0]}
            scale={[0.308, 0.427, 0.308]}
          >
            <mesh
              name="Sphere001"
              geometry={nodes.Sphere001.geometry}
              material={materials.watermelon_green}
            />
            <mesh
              name="Sphere001_1"
              geometry={nodes.Sphere001_1.geometry}
              material={materials.watermelon_black}
            />
          </group>
        </RigidBody>
      )}

      {/* Cut Pliers */}
      {!isItemHeld('cut_pliers') && (
        <RigidBody
          key={`cut_pliers-${getItemPosition('cut_pliers', [0.565, 4.864, -17.027]).join(',')}`}
          type="dynamic"
          position={getItemPosition('cut_pliers', [0.565, 4.864, -17.027])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group
            name="cut_pliers"
            position={[0, 0, 0]}
            rotation={[-Math.PI, -0.268, 0]}
            scale={[0.017, 0.008, 0.024]}
          >
            <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.metal} />
            <mesh
              name="Cube024_1"
              geometry={nodes.Cube024_1.geometry}
              material={materials.watermelon_green}
            />
          </group>
        </RigidBody>
      )}

      {/* Hammer - long object, use cuboid */}
      {!isItemHeld('hammer') && (
        <RigidBody
          key={`hammer-${getItemPosition('hammer', [-0.711, 5.102, -16.354]).join(',')}`}
          type="dynamic"
          position={getItemPosition('hammer', [-0.711, 5.102, -16.354])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.85}
        >
          <group
            name="hammer"
            position={[0, 0, 0]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.181, 0.024, 0.035]}
          >
            <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials.wood2} />
            <mesh name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials.metal} />
          </group>
        </RigidBody>
      )}
      
      {/* Wood Plank - pickable after chipped off */}
      {isChippedOff && !isItemHeld('wood_plank_item') && (
        <RigidBody
          key={`wood_plank_item-${getItemPosition('wood_plank_item', [8.036, -0.5, -3.118]).join(',')}`}
          type="dynamic"
          position={getItemPosition('wood_plank_item', [8.036, -0.5, -3.118])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.85}
        >
          <mesh
            name="wood_plank_item"
            geometry={houseModel.nodes.wood_plank.geometry}
            material={houseModel.materials.wood2}
            position={[0, 0, 0]}
            rotation={[Math.PI / 2, -0.236, 0]}
            scale={[0.273, 0.025, 0.273]}
          />
        </RigidBody>
      )}
      
      {/* Vase - pickable decorative item */}
      {!isItemHeld('vase') && (
        <RigidBody
          key={`vase-${getItemPosition('vase', [1.808, 4.774, -21.72]).join(',')}`}
          type="dynamic"
          position={getItemPosition('vase', [1.808, 4.774, -21.72])}
          colliders="cuboid"
          restitution={0.3}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.9}
        >
          <mesh
            name="vase"
            geometry={houseModel.nodes.vase001.geometry}
            material={houseModel.materials.vase}
            position={[0, 0, 0]}
          />
        </RigidBody>
      )}
    </group>
  );
}

useGLTF.preload('/models/items.glb');
