/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/items.glb --types --keepnames -o src/components/Items.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';
import { RigidBody, type RapierRigidBody } from '@react-three/rapier';
import React from 'react';
import { useItems } from '../store/useItems';
import { usePlank } from '../store/usePlank';
import { useGLTF as useHouseGLTF } from '@react-three/drei';
import { useWell } from '../store/useWell';
import { useFrame } from '@react-three/fiber';
import { useGuillotine } from '../store/useGuillotine';

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    handle: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere001_1: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube052_1: THREE.Mesh;
  };
  materials: {
    metal: THREE.MeshStandardMaterial;
    padlock_key: THREE.MeshStandardMaterial;
    master_key: THREE.MeshStandardMaterial;
    vase: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    safe_key: THREE.MeshStandardMaterial;
    wood2: THREE.MeshStandardMaterial;
    watermelon_green: THREE.MeshStandardMaterial;
    watermelon_black: THREE.MeshStandardMaterial;
  };
};

// Helper component for items that need to follow containers
function ContainerItem({
  itemName,
  bodyType,
  position,
  children,
  ...rigidBodyProps
}: {
  itemName: string;
  bodyType: 'dynamic' | 'kinematicPosition';
  position: [number, number, number];
  children: React.ReactNode;
  [key: string]: any;
}) {
  const rbRef = React.useRef<RapierRigidBody>(null);
  const lastBodyType = React.useRef(bodyType);

  useFrame(() => {
    if (rbRef.current && bodyType === 'kinematicPosition') {
      // Update kinematic body position every frame
      rbRef.current.setTranslation({ x: position[0], y: position[1], z: position[2] }, true);
    }
  });

  // Reset velocity when transitioning to dynamic
  React.useEffect(() => {
    if (lastBodyType.current === 'kinematicPosition' && bodyType === 'dynamic' && rbRef.current) {
      rbRef.current.setLinvel({ x: 0, y: 0, z: 0 }, true);
      rbRef.current.setAngvel({ x: 0, y: 0, z: 0 }, true);
    }
    lastBodyType.current = bodyType;
  }, [bodyType]);

  return (
    <RigidBody ref={rbRef} type={bodyType} position={position} {...rigidBodyProps}>
      {children}
    </RigidBody>
  );
}

export function Items(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/items.glb') as unknown as GLTFResult;
  const houseModel = useHouseGLTF('/models/hauntedHouse.glb') as any;
  const { isItemHeld, getItemPosition, itemSlots, setSpawnPosition, itemInsideWatermelon } = useItems();
  const { isChippedOff } = usePlank();
  const { bucketHeight } = useWell();
  const { itemRevealed } = useGuillotine();
  const [initialized, setInitialized] = React.useState(false);
  const [itemContainers, setItemContainers] = React.useState<Record<string, { type: 'bucket', id: string, basePos: [number, number, number] }>>({});

  // Initialize spawn positions from GLTF empties and detect containers
  React.useEffect(() => {
    if (!initialized && houseModel?.nodes) {
      const containers: Record<string, { type: 'bucket', id: string, basePos: [number, number, number] }> = {};
      
      Object.entries(itemSlots).forEach(([itemName, slotName]) => {
        const empty = houseModel.nodes[slotName];
        if (empty?.position) {
          const pos: [number, number, number] = [
            empty.position.x,
            empty.position.y,
            empty.position.z,
          ];
          setSpawnPosition(itemName, pos);
          
          // Detect if item is in the bucket/well
          if (slotName === 'slot_well') {
            containers[itemName] = { type: 'bucket', id: 'bucket001', basePos: pos };
          }
        } else {
          console.warn(`Empty ${slotName} not found for item ${itemName}`);
        }
      });
      
      setItemContainers(containers);
      setInitialized(true);
    }
  }, [houseModel, itemSlots, setSpawnPosition, initialized]);

  // Helper to get item position with container offset
  const getContainerAdjustedPosition = React.useCallback((itemName: string, basePos: [number, number, number]): [number, number, number] => {
    const pos = getItemPosition(itemName, basePos);
    const container = itemContainers[itemName];
    
    if (!container) return pos;
    
    if (container.type === 'bucket') {
      // Bucket moves up along Y axis
      return [pos[0], pos[1] + bucketHeight, pos[2]];
    }
    
    return pos;
  }, [getItemPosition, itemContainers, bucketHeight]);
  
  // Helper to determine if item should be dynamic or kinematic
  const getItemBodyType = React.useCallback((itemName: string): 'dynamic' | 'kinematicPosition' => {
    const container = itemContainers[itemName];
    
    if (!container) return 'dynamic';
    
    if (container.type === 'bucket') {
      // Item becomes dynamic when bucket is fully raised
      return bucketHeight >= 4.5 ? 'dynamic' : 'kinematicPosition';
    }
    
    return 'dynamic';
  }, [itemContainers, bucketHeight]);

  // Collision groups:
  // - Group 0 (0x0001): Static geometry (floors, walls, furniture)
  // - Group 1 (0x0002): Player
  // - Group 2 (0x0004): Items
  // Format: (filterMask << 16) | membershipGroup
  // Items belong to group 2 and collide with groups 0 and 2 (not player)
  const itemCollisionGroup = (0x0005 << 16) | 0x0004; // Collides with 0x0001 | 0x0004 = 0x0005

  return (
    <group {...props} dispose={null}>
      {/* Padlock Key - small key with CCD */}
      {!isItemHeld('padlock_key') && (itemInsideWatermelon !== 'padlock_key' || itemRevealed) && (
        <ContainerItem
          key={`padlock_key-${getItemBodyType('padlock_key')}-${itemContainers['padlock_key']?.id || 'none'}`}
          itemName="padlock_key"
          bodyType={getItemBodyType('padlock_key')}
          position={getContainerAdjustedPosition('padlock_key', [-1.744, 4.512, -16.36])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group name="padlock_key" position={[0, 0, 0]} scale={[0.054, 0.014, 0.042]}>
            <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.metal} />
            <mesh
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials.padlock_key}
            />
          </group>
        </ContainerItem>
      )}

      {/* Master Key - small key with CCD */}
      {!isItemHeld('master_key') && (
        <ContainerItem
          key={`master_key-${getItemBodyType('master_key')}-${itemContainers['master_key']?.id || 'none'}`}
          itemName="master_key"
          bodyType={getItemBodyType('master_key')}
          position={getContainerAdjustedPosition('master_key', [-1.744, 4.512, -16.597])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group name="master_key" position={[0, 0, 0]} scale={[0.054, 0.014, 0.042]}>
            <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.metal} />
            <mesh
              name="Cube003_1"
              geometry={nodes.Cube003_1.geometry}
              material={materials.master_key}
            />
          </group>
        </ContainerItem>
      )}

      {/* Card - thin flat object with CCD */}
      {!isItemHeld('card') && (itemInsideWatermelon !== 'card' || itemRevealed) && (
        <ContainerItem
          key={`card-${getItemBodyType('card')}-${itemContainers['card']?.id || 'none'}`}
          itemName="card"
          bodyType={getItemBodyType('card')}
          position={getContainerAdjustedPosition('card', [-0.344, 5.349, -16.871])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group name="card" position={[0, 0, 0]} scale={[0.145, 0.007, 0.06]}>
            <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.vase} />
            <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.black} />
          </group>
        </ContainerItem>
      )}

      {/* Safe Key - small key with CCD */}
      {!isItemHeld('safe_key') && (itemInsideWatermelon !== 'safe_key' || itemRevealed) && (
        <ContainerItem
          key={`safe_key-${getItemBodyType('safe_key')}-${itemContainers['safe_key']?.id || 'none'}`}
          itemName="safe_key"
          bodyType={getItemBodyType('safe_key')}
          position={getContainerAdjustedPosition('safe_key', [-1.744, 4.512, -16.957])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group name="safe_key" position={[0, 0, 0]} scale={[0.054, 0.014, 0.042]}>
            <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.metal} />
            <mesh
              name="Cube010_1"
              geometry={nodes.Cube010_1.geometry}
              material={materials.safe_key}
            />
          </group>
        </ContainerItem>
      )}

      {/* Handle - cylindrical object */}
      {!isItemHeld('handle') && (
        <ContainerItem
          key={`handle-${getItemBodyType('handle')}-${itemContainers['handle']?.id || 'none'}`}
          itemName="handle"
          bodyType={getItemBodyType('handle')}
          position={getContainerAdjustedPosition('handle', [-0.396, 5.348, -17.387])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.85}
        >
          <mesh
            name="handle"
            geometry={nodes.handle.geometry}
            material={materials.wood2}
            position={[0, 0, 0]}
          />
        </ContainerItem>
      )}

      {/* Watermelon - round object, use ball collider */}
      {!isItemHeld('watermelon') && (
        <ContainerItem
          key={`watermelon-${getItemBodyType('watermelon')}-${itemContainers['watermelon']?.id || 'none'}`}
          itemName="watermelon"
          bodyType={getItemBodyType('watermelon')}
          position={getContainerAdjustedPosition('watermelon', [-0.106, 4.975, -15.882])}
          colliders="ball"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.9}
        >
          <group
            name="watermelon"
            position={[0, 0, 0]}
            rotation={[-Math.PI / 2, 1.57, 0]}
            scale={[0.308, 0.427, 0.308]}
          >
            <mesh
              name="Sphere001"
              geometry={nodes.Sphere001.geometry}
              material={materials.watermelon_green}
            />
            <mesh
              name="Sphere001_1"
              geometry={nodes.Sphere001_1.geometry}
              material={materials.watermelon_black}
            />
          </group>
        </ContainerItem>
      )}

      {/* Cut Pliers */}
      {!isItemHeld('cut_pliers') && (
        <ContainerItem
          key={`cut_pliers-${getItemBodyType('cut_pliers')}-${itemContainers['cut_pliers']?.id || 'none'}`}
          itemName="cut_pliers"
          bodyType={getItemBodyType('cut_pliers')}
          position={getContainerAdjustedPosition('cut_pliers', [0.565, 4.864, -17.027])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.8}
        >
          <group
            name="cut_pliers"
            position={[0, 0, 0]}
            rotation={[-Math.PI, -0.268, 0]}
            scale={[0.017, 0.008, 0.024]}
          >
            <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials.metal} />
            <mesh
              name="Cube024_1"
              geometry={nodes.Cube024_1.geometry}
              material={materials.watermelon_green}
            />
          </group>
        </ContainerItem>
      )}

      {/* Hammer - long object, use cuboid */}
      {!isItemHeld('hammer') && (
        <ContainerItem
          key={`hammer-${getItemBodyType('hammer')}-${itemContainers['hammer']?.id || 'none'}`}
          itemName="hammer"
          bodyType={getItemBodyType('hammer')}
          position={getContainerAdjustedPosition('hammer', [-0.711, 5.102, -16.354])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.85}
        >
          <group
            name="hammer"
            position={[0, 0, 0]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.181, 0.024, 0.035]}
          >
            <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials.wood2} />
            <mesh name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials.metal} />
          </group>
        </ContainerItem>
      )}
      
      {/* Wood Plank - pickable after chipped off */}
      {isChippedOff && !isItemHeld('wood_plank_item') && (
        <RigidBody
          key={`wood_plank_item-${getItemPosition('wood_plank_item', [8.036, -0.5, -3.118]).join(',')}`}
          type="dynamic"
          position={getItemPosition('wood_plank_item', [8.036, -0.5, -3.118])}
          colliders="cuboid"
          restitution={0.2}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.85}
        >
          <mesh
            name="wood_plank_item"
            geometry={houseModel.nodes.wood_plank.geometry}
            material={houseModel.materials.wood2}
            position={[0, 0, 0]}
            rotation={[Math.PI / 2, -0.236, 0]}
            scale={[0.273, 0.025, 0.273]}
          />
        </RigidBody>
      )}
      
      {/* Vase - pickable decorative item */}
      {!isItemHeld('vase') && (
        <RigidBody
          key={`vase-${getItemPosition('vase', [1.808, 4.774, -21.72]).join(',')}`}
          type="dynamic"
          position={getItemPosition('vase', [1.808, 4.774, -21.72])}
          colliders="cuboid"
          restitution={0.3}
          friction={0.8}
          canSleep={true}
          ccd={true}
          collisionGroups={itemCollisionGroup}
          scale={0.9}
        >
          <mesh
            name="vase"
            geometry={houseModel.nodes.vase001.geometry}
            material={houseModel.materials.vase}
            position={[0, 0, 0]}
          />
        </RigidBody>
      )}
    </group>
  );
}

useGLTF.preload('/models/items.glb');
